// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: moneydashboard/v4/account_groups.proto

package mdv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,3,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountGroup) Reset() {
	*x = AccountGroup{}
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountGroup) ProtoMessage() {}

func (x *AccountGroup) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountGroup.ProtoReflect.Descriptor instead.
func (*AccountGroup) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_account_groups_proto_rawDescGZIP(), []int{0}
}

func (x *AccountGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountGroup) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

type GetAccountGroupByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountGroupByIdRequest) Reset() {
	*x = GetAccountGroupByIdRequest{}
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountGroupByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountGroupByIdRequest) ProtoMessage() {}

func (x *GetAccountGroupByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountGroupByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountGroupByIdRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_account_groups_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountGroupByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccountGroupByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountGroup  *AccountGroup          `protobuf:"bytes,1,opt,name=account_group,json=accountGroup,proto3" json:"account_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountGroupByIdResponse) Reset() {
	*x = GetAccountGroupByIdResponse{}
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountGroupByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountGroupByIdResponse) ProtoMessage() {}

func (x *GetAccountGroupByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountGroupByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountGroupByIdResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_account_groups_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountGroupByIdResponse) GetAccountGroup() *AccountGroup {
	if x != nil {
		return x.AccountGroup
	}
	return nil
}

type GetAllAccountGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountGroupsRequest) Reset() {
	*x = GetAllAccountGroupsRequest{}
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountGroupsRequest) ProtoMessage() {}

func (x *GetAllAccountGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAccountGroupsRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_account_groups_proto_rawDescGZIP(), []int{3}
}

type GetAllAccountGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountGroups []*AccountGroup        `protobuf:"bytes,1,rep,name=account_groups,json=accountGroups,proto3" json:"account_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountGroupsResponse) Reset() {
	*x = GetAllAccountGroupsResponse{}
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountGroupsResponse) ProtoMessage() {}

func (x *GetAllAccountGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAccountGroupsResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_account_groups_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllAccountGroupsResponse) GetAccountGroups() []*AccountGroup {
	if x != nil {
		return x.AccountGroups
	}
	return nil
}

type UpsertAccountGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountGroup  *AccountGroup          `protobuf:"bytes,1,opt,name=account_group,json=accountGroup,proto3" json:"account_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAccountGroupRequest) Reset() {
	*x = UpsertAccountGroupRequest{}
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAccountGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountGroupRequest) ProtoMessage() {}

func (x *UpsertAccountGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountGroupRequest.ProtoReflect.Descriptor instead.
func (*UpsertAccountGroupRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_account_groups_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertAccountGroupRequest) GetAccountGroup() *AccountGroup {
	if x != nil {
		return x.AccountGroup
	}
	return nil
}

type UpsertAccountGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAccountGroupResponse) Reset() {
	*x = UpsertAccountGroupResponse{}
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAccountGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountGroupResponse) ProtoMessage() {}

func (x *UpsertAccountGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_account_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountGroupResponse.ProtoReflect.Descriptor instead.
func (*UpsertAccountGroupResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_account_groups_proto_rawDescGZIP(), []int{6}
}

var File_moneydashboard_v4_account_groups_proto protoreflect.FileDescriptor

const file_moneydashboard_v4_account_groups_proto_rawDesc = "" +
	"\n" +
	"&moneydashboard/v4/account_groups.proto\x12\x11moneydashboard.v4\"W\n" +
	"\fAccountGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdisplay_order\x18\x03 \x01(\x05R\fdisplayOrder\",\n" +
	"\x1aGetAccountGroupByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x1bGetAccountGroupByIdResponse\x12D\n" +
	"\raccount_group\x18\x01 \x01(\v2\x1f.moneydashboard.v4.AccountGroupR\faccountGroup\"\x1c\n" +
	"\x1aGetAllAccountGroupsRequest\"e\n" +
	"\x1bGetAllAccountGroupsResponse\x12F\n" +
	"\x0eaccount_groups\x18\x01 \x03(\v2\x1f.moneydashboard.v4.AccountGroupR\raccountGroups\"a\n" +
	"\x19UpsertAccountGroupRequest\x12D\n" +
	"\raccount_group\x18\x01 \x01(\v2\x1f.moneydashboard.v4.AccountGroupR\faccountGroup\"\x1c\n" +
	"\x1aUpsertAccountGroupResponse2\xf6\x02\n" +
	"\x15MDAccountGroupService\x12t\n" +
	"\x13GetAccountGroupById\x12-.moneydashboard.v4.GetAccountGroupByIdRequest\x1a..moneydashboard.v4.GetAccountGroupByIdResponse\x12t\n" +
	"\x13GetAllAccountGroups\x12-.moneydashboard.v4.GetAllAccountGroupsRequest\x1a..moneydashboard.v4.GetAllAccountGroupsResponse\x12q\n" +
	"\x12UpsertAccountGroup\x12,.moneydashboard.v4.UpsertAccountGroupRequest\x1a-.moneydashboard.v4.UpsertAccountGroupResponseBQZOgithub.com/markormesher/money-dashboard/internal/api_gen/moneydashboard/v4;mdv4b\x06proto3"

var (
	file_moneydashboard_v4_account_groups_proto_rawDescOnce sync.Once
	file_moneydashboard_v4_account_groups_proto_rawDescData []byte
)

func file_moneydashboard_v4_account_groups_proto_rawDescGZIP() []byte {
	file_moneydashboard_v4_account_groups_proto_rawDescOnce.Do(func() {
		file_moneydashboard_v4_account_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_account_groups_proto_rawDesc), len(file_moneydashboard_v4_account_groups_proto_rawDesc)))
	})
	return file_moneydashboard_v4_account_groups_proto_rawDescData
}

var file_moneydashboard_v4_account_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_moneydashboard_v4_account_groups_proto_goTypes = []any{
	(*AccountGroup)(nil),                // 0: moneydashboard.v4.AccountGroup
	(*GetAccountGroupByIdRequest)(nil),  // 1: moneydashboard.v4.GetAccountGroupByIdRequest
	(*GetAccountGroupByIdResponse)(nil), // 2: moneydashboard.v4.GetAccountGroupByIdResponse
	(*GetAllAccountGroupsRequest)(nil),  // 3: moneydashboard.v4.GetAllAccountGroupsRequest
	(*GetAllAccountGroupsResponse)(nil), // 4: moneydashboard.v4.GetAllAccountGroupsResponse
	(*UpsertAccountGroupRequest)(nil),   // 5: moneydashboard.v4.UpsertAccountGroupRequest
	(*UpsertAccountGroupResponse)(nil),  // 6: moneydashboard.v4.UpsertAccountGroupResponse
}
var file_moneydashboard_v4_account_groups_proto_depIdxs = []int32{
	0, // 0: moneydashboard.v4.GetAccountGroupByIdResponse.account_group:type_name -> moneydashboard.v4.AccountGroup
	0, // 1: moneydashboard.v4.GetAllAccountGroupsResponse.account_groups:type_name -> moneydashboard.v4.AccountGroup
	0, // 2: moneydashboard.v4.UpsertAccountGroupRequest.account_group:type_name -> moneydashboard.v4.AccountGroup
	1, // 3: moneydashboard.v4.MDAccountGroupService.GetAccountGroupById:input_type -> moneydashboard.v4.GetAccountGroupByIdRequest
	3, // 4: moneydashboard.v4.MDAccountGroupService.GetAllAccountGroups:input_type -> moneydashboard.v4.GetAllAccountGroupsRequest
	5, // 5: moneydashboard.v4.MDAccountGroupService.UpsertAccountGroup:input_type -> moneydashboard.v4.UpsertAccountGroupRequest
	2, // 6: moneydashboard.v4.MDAccountGroupService.GetAccountGroupById:output_type -> moneydashboard.v4.GetAccountGroupByIdResponse
	4, // 7: moneydashboard.v4.MDAccountGroupService.GetAllAccountGroups:output_type -> moneydashboard.v4.GetAllAccountGroupsResponse
	6, // 8: moneydashboard.v4.MDAccountGroupService.UpsertAccountGroup:output_type -> moneydashboard.v4.UpsertAccountGroupResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_moneydashboard_v4_account_groups_proto_init() }
func file_moneydashboard_v4_account_groups_proto_init() {
	if File_moneydashboard_v4_account_groups_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_account_groups_proto_rawDesc), len(file_moneydashboard_v4_account_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moneydashboard_v4_account_groups_proto_goTypes,
		DependencyIndexes: file_moneydashboard_v4_account_groups_proto_depIdxs,
		MessageInfos:      file_moneydashboard_v4_account_groups_proto_msgTypes,
	}.Build()
	File_moneydashboard_v4_account_groups_proto = out.File
	file_moneydashboard_v4_account_groups_proto_goTypes = nil
	file_moneydashboard_v4_account_groups_proto_depIdxs = nil
}
