// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: moneydashboard/v4/accounts.proto

package mdv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notes                string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	IsIsa                bool                   `protobuf:"varint,4,opt,name=is_isa,json=isIsa,proto3" json:"is_isa,omitempty"`
	IsPension            bool                   `protobuf:"varint,5,opt,name=is_pension,json=isPension,proto3" json:"is_pension,omitempty"`
	ExcludeFromEnvelopes bool                   `protobuf:"varint,6,opt,name=exclude_from_envelopes,json=excludeFromEnvelopes,proto3" json:"exclude_from_envelopes,omitempty"`
	ExcludeFromReports   bool                   `protobuf:"varint,7,opt,name=exclude_from_reports,json=excludeFromReports,proto3" json:"exclude_from_reports,omitempty"`
	Active               bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	AccountGroup         *AccountGroup          `protobuf:"bytes,9,opt,name=account_group,json=accountGroup,proto3" json:"account_group,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Account) GetIsIsa() bool {
	if x != nil {
		return x.IsIsa
	}
	return false
}

func (x *Account) GetIsPension() bool {
	if x != nil {
		return x.IsPension
	}
	return false
}

func (x *Account) GetExcludeFromEnvelopes() bool {
	if x != nil {
		return x.ExcludeFromEnvelopes
	}
	return false
}

func (x *Account) GetExcludeFromReports() bool {
	if x != nil {
		return x.ExcludeFromReports
	}
	return false
}

func (x *Account) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Account) GetAccountGroup() *AccountGroup {
	if x != nil {
		return x.AccountGroup
	}
	return nil
}

type GetAccountByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdRequest) Reset() {
	*x = GetAccountByIdRequest{}
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdRequest) ProtoMessage() {}

func (x *GetAccountByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIdRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccountByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdResponse) Reset() {
	*x = GetAccountByIdResponse{}
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdResponse) ProtoMessage() {}

func (x *GetAccountByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByIdResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountByIdResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAllAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountsRequest) Reset() {
	*x = GetAllAccountsRequest{}
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountsRequest) ProtoMessage() {}

func (x *GetAllAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAccountsRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_accounts_proto_rawDescGZIP(), []int{3}
}

type GetAllAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountsResponse) Reset() {
	*x = GetAllAccountsResponse{}
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountsResponse) ProtoMessage() {}

func (x *GetAllAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAccountsResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type UpsertAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAccountRequest) Reset() {
	*x = UpsertAccountRequest{}
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountRequest) ProtoMessage() {}

func (x *UpsertAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountRequest.ProtoReflect.Descriptor instead.
func (*UpsertAccountRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type UpsertAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAccountResponse) Reset() {
	*x = UpsertAccountResponse{}
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountResponse) ProtoMessage() {}

func (x *UpsertAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountResponse.ProtoReflect.Descriptor instead.
func (*UpsertAccountResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_accounts_proto_rawDescGZIP(), []int{6}
}

var File_moneydashboard_v4_accounts_proto protoreflect.FileDescriptor

const file_moneydashboard_v4_accounts_proto_rawDesc = "" +
	"\n" +
	" moneydashboard/v4/accounts.proto\x12\x11moneydashboard.v4\x1a&moneydashboard/v4/account_groups.proto\"\xbf\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x15\n" +
	"\x06is_isa\x18\x04 \x01(\bR\x05isIsa\x12\x1d\n" +
	"\n" +
	"is_pension\x18\x05 \x01(\bR\tisPension\x124\n" +
	"\x16exclude_from_envelopes\x18\x06 \x01(\bR\x14excludeFromEnvelopes\x120\n" +
	"\x14exclude_from_reports\x18\a \x01(\bR\x12excludeFromReports\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12D\n" +
	"\raccount_group\x18\t \x01(\v2\x1f.moneydashboard.v4.AccountGroupR\faccountGroup\"'\n" +
	"\x15GetAccountByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x16GetAccountByIdResponse\x124\n" +
	"\aaccount\x18\x01 \x01(\v2\x1a.moneydashboard.v4.AccountR\aaccount\"\x17\n" +
	"\x15GetAllAccountsRequest\"P\n" +
	"\x16GetAllAccountsResponse\x126\n" +
	"\baccounts\x18\x01 \x03(\v2\x1a.moneydashboard.v4.AccountR\baccounts\"L\n" +
	"\x14UpsertAccountRequest\x124\n" +
	"\aaccount\x18\x01 \x01(\v2\x1a.moneydashboard.v4.AccountR\aaccount\"\x17\n" +
	"\x15UpsertAccountResponse2\xc4\x02\n" +
	"\x10MDAccountService\x12e\n" +
	"\x0eGetAccountById\x12(.moneydashboard.v4.GetAccountByIdRequest\x1a).moneydashboard.v4.GetAccountByIdResponse\x12e\n" +
	"\x0eGetAllAccounts\x12(.moneydashboard.v4.GetAllAccountsRequest\x1a).moneydashboard.v4.GetAllAccountsResponse\x12b\n" +
	"\rUpsertAccount\x12'.moneydashboard.v4.UpsertAccountRequest\x1a(.moneydashboard.v4.UpsertAccountResponseBQZOgithub.com/markormesher/money-dashboard/internal/api_gen/moneydashboard/v4;mdv4b\x06proto3"

var (
	file_moneydashboard_v4_accounts_proto_rawDescOnce sync.Once
	file_moneydashboard_v4_accounts_proto_rawDescData []byte
)

func file_moneydashboard_v4_accounts_proto_rawDescGZIP() []byte {
	file_moneydashboard_v4_accounts_proto_rawDescOnce.Do(func() {
		file_moneydashboard_v4_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_accounts_proto_rawDesc), len(file_moneydashboard_v4_accounts_proto_rawDesc)))
	})
	return file_moneydashboard_v4_accounts_proto_rawDescData
}

var file_moneydashboard_v4_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_moneydashboard_v4_accounts_proto_goTypes = []any{
	(*Account)(nil),                // 0: moneydashboard.v4.Account
	(*GetAccountByIdRequest)(nil),  // 1: moneydashboard.v4.GetAccountByIdRequest
	(*GetAccountByIdResponse)(nil), // 2: moneydashboard.v4.GetAccountByIdResponse
	(*GetAllAccountsRequest)(nil),  // 3: moneydashboard.v4.GetAllAccountsRequest
	(*GetAllAccountsResponse)(nil), // 4: moneydashboard.v4.GetAllAccountsResponse
	(*UpsertAccountRequest)(nil),   // 5: moneydashboard.v4.UpsertAccountRequest
	(*UpsertAccountResponse)(nil),  // 6: moneydashboard.v4.UpsertAccountResponse
	(*AccountGroup)(nil),           // 7: moneydashboard.v4.AccountGroup
}
var file_moneydashboard_v4_accounts_proto_depIdxs = []int32{
	7, // 0: moneydashboard.v4.Account.account_group:type_name -> moneydashboard.v4.AccountGroup
	0, // 1: moneydashboard.v4.GetAccountByIdResponse.account:type_name -> moneydashboard.v4.Account
	0, // 2: moneydashboard.v4.GetAllAccountsResponse.accounts:type_name -> moneydashboard.v4.Account
	0, // 3: moneydashboard.v4.UpsertAccountRequest.account:type_name -> moneydashboard.v4.Account
	1, // 4: moneydashboard.v4.MDAccountService.GetAccountById:input_type -> moneydashboard.v4.GetAccountByIdRequest
	3, // 5: moneydashboard.v4.MDAccountService.GetAllAccounts:input_type -> moneydashboard.v4.GetAllAccountsRequest
	5, // 6: moneydashboard.v4.MDAccountService.UpsertAccount:input_type -> moneydashboard.v4.UpsertAccountRequest
	2, // 7: moneydashboard.v4.MDAccountService.GetAccountById:output_type -> moneydashboard.v4.GetAccountByIdResponse
	4, // 8: moneydashboard.v4.MDAccountService.GetAllAccounts:output_type -> moneydashboard.v4.GetAllAccountsResponse
	6, // 9: moneydashboard.v4.MDAccountService.UpsertAccount:output_type -> moneydashboard.v4.UpsertAccountResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_moneydashboard_v4_accounts_proto_init() }
func file_moneydashboard_v4_accounts_proto_init() {
	if File_moneydashboard_v4_accounts_proto != nil {
		return
	}
	file_moneydashboard_v4_account_groups_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_accounts_proto_rawDesc), len(file_moneydashboard_v4_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moneydashboard_v4_accounts_proto_goTypes,
		DependencyIndexes: file_moneydashboard_v4_accounts_proto_depIdxs,
		MessageInfos:      file_moneydashboard_v4_accounts_proto_msgTypes,
	}.Build()
	File_moneydashboard_v4_accounts_proto = out.File
	file_moneydashboard_v4_accounts_proto_goTypes = nil
	file_moneydashboard_v4_accounts_proto_depIdxs = nil
}
