// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: moneydashboard/v4/holdings.proto

package mdv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Holding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Currency      *Currency              `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	Account       *Account               `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holding) Reset() {
	*x = Holding{}
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holding) ProtoMessage() {}

func (x *Holding) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holding.ProtoReflect.Descriptor instead.
func (*Holding) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_holdings_proto_rawDescGZIP(), []int{0}
}

func (x *Holding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Holding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Holding) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Holding) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *Holding) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Holding) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetHoldingByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingByIdRequest) Reset() {
	*x = GetHoldingByIdRequest{}
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingByIdRequest) ProtoMessage() {}

func (x *GetHoldingByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingByIdRequest.ProtoReflect.Descriptor instead.
func (*GetHoldingByIdRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_holdings_proto_rawDescGZIP(), []int{1}
}

func (x *GetHoldingByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHoldingByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holding       *Holding               `protobuf:"bytes,1,opt,name=holding,proto3" json:"holding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingByIdResponse) Reset() {
	*x = GetHoldingByIdResponse{}
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingByIdResponse) ProtoMessage() {}

func (x *GetHoldingByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingByIdResponse.ProtoReflect.Descriptor instead.
func (*GetHoldingByIdResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_holdings_proto_rawDescGZIP(), []int{2}
}

func (x *GetHoldingByIdResponse) GetHolding() *Holding {
	if x != nil {
		return x.Holding
	}
	return nil
}

type GetAllHoldingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHoldingsRequest) Reset() {
	*x = GetAllHoldingsRequest{}
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHoldingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHoldingsRequest) ProtoMessage() {}

func (x *GetAllHoldingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHoldingsRequest.ProtoReflect.Descriptor instead.
func (*GetAllHoldingsRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_holdings_proto_rawDescGZIP(), []int{3}
}

type GetAllHoldingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holdings      []*Holding             `protobuf:"bytes,1,rep,name=holdings,proto3" json:"holdings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHoldingsResponse) Reset() {
	*x = GetAllHoldingsResponse{}
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHoldingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHoldingsResponse) ProtoMessage() {}

func (x *GetAllHoldingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHoldingsResponse.ProtoReflect.Descriptor instead.
func (*GetAllHoldingsResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_holdings_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllHoldingsResponse) GetHoldings() []*Holding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

type UpsertHoldingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holding       *Holding               `protobuf:"bytes,1,opt,name=holding,proto3" json:"holding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertHoldingRequest) Reset() {
	*x = UpsertHoldingRequest{}
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertHoldingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertHoldingRequest) ProtoMessage() {}

func (x *UpsertHoldingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertHoldingRequest.ProtoReflect.Descriptor instead.
func (*UpsertHoldingRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_holdings_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertHoldingRequest) GetHolding() *Holding {
	if x != nil {
		return x.Holding
	}
	return nil
}

type UpsertHoldingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertHoldingResponse) Reset() {
	*x = UpsertHoldingResponse{}
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertHoldingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertHoldingResponse) ProtoMessage() {}

func (x *UpsertHoldingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_holdings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertHoldingResponse.ProtoReflect.Descriptor instead.
func (*UpsertHoldingResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_holdings_proto_rawDescGZIP(), []int{6}
}

var File_moneydashboard_v4_holdings_proto protoreflect.FileDescriptor

const file_moneydashboard_v4_holdings_proto_rawDesc = "" +
	"\n" +
	" moneydashboard/v4/holdings.proto\x12\x11moneydashboard.v4\x1a moneydashboard/v4/accounts.proto\x1a\x1emoneydashboard/v4/assets.proto\x1a\"moneydashboard/v4/currencies.proto\"\xe4\x01\n" +
	"\aHolding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x127\n" +
	"\bcurrency\x18\x04 \x01(\v2\x1b.moneydashboard.v4.CurrencyR\bcurrency\x12.\n" +
	"\x05asset\x18\x05 \x01(\v2\x18.moneydashboard.v4.AssetR\x05asset\x124\n" +
	"\aaccount\x18\x06 \x01(\v2\x1a.moneydashboard.v4.AccountR\aaccount\"'\n" +
	"\x15GetHoldingByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x16GetHoldingByIdResponse\x124\n" +
	"\aholding\x18\x01 \x01(\v2\x1a.moneydashboard.v4.HoldingR\aholding\"\x17\n" +
	"\x15GetAllHoldingsRequest\"P\n" +
	"\x16GetAllHoldingsResponse\x126\n" +
	"\bholdings\x18\x01 \x03(\v2\x1a.moneydashboard.v4.HoldingR\bholdings\"L\n" +
	"\x14UpsertHoldingRequest\x124\n" +
	"\aholding\x18\x01 \x01(\v2\x1a.moneydashboard.v4.HoldingR\aholding\"\x17\n" +
	"\x15UpsertHoldingResponse2\xc4\x02\n" +
	"\x10MDHoldingService\x12e\n" +
	"\x0eGetHoldingById\x12(.moneydashboard.v4.GetHoldingByIdRequest\x1a).moneydashboard.v4.GetHoldingByIdResponse\x12e\n" +
	"\x0eGetAllHoldings\x12(.moneydashboard.v4.GetAllHoldingsRequest\x1a).moneydashboard.v4.GetAllHoldingsResponse\x12b\n" +
	"\rUpsertHolding\x12'.moneydashboard.v4.UpsertHoldingRequest\x1a(.moneydashboard.v4.UpsertHoldingResponseBQZOgithub.com/markormesher/money-dashboard/internal/api_gen/moneydashboard/v4;mdv4b\x06proto3"

var (
	file_moneydashboard_v4_holdings_proto_rawDescOnce sync.Once
	file_moneydashboard_v4_holdings_proto_rawDescData []byte
)

func file_moneydashboard_v4_holdings_proto_rawDescGZIP() []byte {
	file_moneydashboard_v4_holdings_proto_rawDescOnce.Do(func() {
		file_moneydashboard_v4_holdings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_holdings_proto_rawDesc), len(file_moneydashboard_v4_holdings_proto_rawDesc)))
	})
	return file_moneydashboard_v4_holdings_proto_rawDescData
}

var file_moneydashboard_v4_holdings_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_moneydashboard_v4_holdings_proto_goTypes = []any{
	(*Holding)(nil),                // 0: moneydashboard.v4.Holding
	(*GetHoldingByIdRequest)(nil),  // 1: moneydashboard.v4.GetHoldingByIdRequest
	(*GetHoldingByIdResponse)(nil), // 2: moneydashboard.v4.GetHoldingByIdResponse
	(*GetAllHoldingsRequest)(nil),  // 3: moneydashboard.v4.GetAllHoldingsRequest
	(*GetAllHoldingsResponse)(nil), // 4: moneydashboard.v4.GetAllHoldingsResponse
	(*UpsertHoldingRequest)(nil),   // 5: moneydashboard.v4.UpsertHoldingRequest
	(*UpsertHoldingResponse)(nil),  // 6: moneydashboard.v4.UpsertHoldingResponse
	(*Currency)(nil),               // 7: moneydashboard.v4.Currency
	(*Asset)(nil),                  // 8: moneydashboard.v4.Asset
	(*Account)(nil),                // 9: moneydashboard.v4.Account
}
var file_moneydashboard_v4_holdings_proto_depIdxs = []int32{
	7, // 0: moneydashboard.v4.Holding.currency:type_name -> moneydashboard.v4.Currency
	8, // 1: moneydashboard.v4.Holding.asset:type_name -> moneydashboard.v4.Asset
	9, // 2: moneydashboard.v4.Holding.account:type_name -> moneydashboard.v4.Account
	0, // 3: moneydashboard.v4.GetHoldingByIdResponse.holding:type_name -> moneydashboard.v4.Holding
	0, // 4: moneydashboard.v4.GetAllHoldingsResponse.holdings:type_name -> moneydashboard.v4.Holding
	0, // 5: moneydashboard.v4.UpsertHoldingRequest.holding:type_name -> moneydashboard.v4.Holding
	1, // 6: moneydashboard.v4.MDHoldingService.GetHoldingById:input_type -> moneydashboard.v4.GetHoldingByIdRequest
	3, // 7: moneydashboard.v4.MDHoldingService.GetAllHoldings:input_type -> moneydashboard.v4.GetAllHoldingsRequest
	5, // 8: moneydashboard.v4.MDHoldingService.UpsertHolding:input_type -> moneydashboard.v4.UpsertHoldingRequest
	2, // 9: moneydashboard.v4.MDHoldingService.GetHoldingById:output_type -> moneydashboard.v4.GetHoldingByIdResponse
	4, // 10: moneydashboard.v4.MDHoldingService.GetAllHoldings:output_type -> moneydashboard.v4.GetAllHoldingsResponse
	6, // 11: moneydashboard.v4.MDHoldingService.UpsertHolding:output_type -> moneydashboard.v4.UpsertHoldingResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_moneydashboard_v4_holdings_proto_init() }
func file_moneydashboard_v4_holdings_proto_init() {
	if File_moneydashboard_v4_holdings_proto != nil {
		return
	}
	file_moneydashboard_v4_accounts_proto_init()
	file_moneydashboard_v4_assets_proto_init()
	file_moneydashboard_v4_currencies_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_holdings_proto_rawDesc), len(file_moneydashboard_v4_holdings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moneydashboard_v4_holdings_proto_goTypes,
		DependencyIndexes: file_moneydashboard_v4_holdings_proto_depIdxs,
		MessageInfos:      file_moneydashboard_v4_holdings_proto_msgTypes,
	}.Build()
	File_moneydashboard_v4_holdings_proto = out.File
	file_moneydashboard_v4_holdings_proto_goTypes = nil
	file_moneydashboard_v4_holdings_proto_depIdxs = nil
}
