// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: moneydashboard/v4/transactions.proto

package mdv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          int64                  `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	BudgetDate    int64                  `protobuf:"varint,3,opt,name=budget_date,json=budgetDate,proto3" json:"budget_date,omitempty"`
	CreationDate  int64                  `protobuf:"varint,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Payee         string                 `protobuf:"bytes,5,opt,name=payee,proto3" json:"payee,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	UnitValue     float64                `protobuf:"fixed64,8,opt,name=unit_value,json=unitValue,proto3" json:"unit_value,omitempty"`
	Deleted       bool                   `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Holding       *Holding               `protobuf:"bytes,10,opt,name=holding,proto3" json:"holding,omitempty"`
	Category      *Category              `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Transaction) GetBudgetDate() int64 {
	if x != nil {
		return x.BudgetDate
	}
	return 0
}

func (x *Transaction) GetCreationDate() int64 {
	if x != nil {
		return x.CreationDate
	}
	return 0
}

func (x *Transaction) GetPayee() string {
	if x != nil {
		return x.Payee
	}
	return ""
}

func (x *Transaction) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetUnitValue() float64 {
	if x != nil {
		return x.UnitValue
	}
	return 0
}

func (x *Transaction) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Transaction) GetHolding() *Holding {
	if x != nil {
		return x.Holding
	}
	return nil
}

func (x *Transaction) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetTransactionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByIdRequest) Reset() {
	*x = GetTransactionByIdRequest{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIdRequest) ProtoMessage() {}

func (x *GetTransactionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByIdRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByIdResponse) Reset() {
	*x = GetTransactionByIdResponse{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIdResponse) ProtoMessage() {}

func (x *GetTransactionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionByIdResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionByIdResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	SearchPattern string                 `protobuf:"bytes,3,opt,name=search_pattern,json=searchPattern,proto3" json:"search_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionPageRequest) Reset() {
	*x = GetTransactionPageRequest{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionPageRequest) ProtoMessage() {}

func (x *GetTransactionPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionPageRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionPageRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionPageRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetTransactionPageRequest) GetSearchPattern() string {
	if x != nil {
		return x.SearchPattern
	}
	return ""
}

type GetTransactionPageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Total            int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	FilteredTotal    int32                  `protobuf:"varint,2,opt,name=filtered_total,json=filteredTotal,proto3" json:"filtered_total,omitempty"`
	FilteredEntities []*Transaction         `protobuf:"bytes,3,rep,name=filtered_entities,json=filteredEntities,proto3" json:"filtered_entities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionPageResponse) Reset() {
	*x = GetTransactionPageResponse{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionPageResponse) ProtoMessage() {}

func (x *GetTransactionPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionPageResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionPageResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionPageResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTransactionPageResponse) GetFilteredTotal() int32 {
	if x != nil {
		return x.FilteredTotal
	}
	return 0
}

func (x *GetTransactionPageResponse) GetFilteredEntities() []*Transaction {
	if x != nil {
		return x.FilteredEntities
	}
	return nil
}

type UpsertTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTransactionRequest) Reset() {
	*x = UpsertTransactionRequest{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTransactionRequest) ProtoMessage() {}

func (x *UpsertTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpsertTransactionRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type UpsertTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTransactionResponse) Reset() {
	*x = UpsertTransactionResponse{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTransactionResponse) ProtoMessage() {}

func (x *UpsertTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTransactionResponse.ProtoReflect.Descriptor instead.
func (*UpsertTransactionResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{6}
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionResponse) Reset() {
	*x = DeleteTransactionResponse{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionResponse) ProtoMessage() {}

func (x *DeleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{8}
}

type GetPayeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayeesRequest) Reset() {
	*x = GetPayeesRequest{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayeesRequest) ProtoMessage() {}

func (x *GetPayeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayeesRequest.ProtoReflect.Descriptor instead.
func (*GetPayeesRequest) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{9}
}

type GetPayeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payees        []string               `protobuf:"bytes,1,rep,name=payees,proto3" json:"payees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayeesResponse) Reset() {
	*x = GetPayeesResponse{}
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayeesResponse) ProtoMessage() {}

func (x *GetPayeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneydashboard_v4_transactions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayeesResponse.ProtoReflect.Descriptor instead.
func (*GetPayeesResponse) Descriptor() ([]byte, []int) {
	return file_moneydashboard_v4_transactions_proto_rawDescGZIP(), []int{10}
}

func (x *GetPayeesResponse) GetPayees() []string {
	if x != nil {
		return x.Payees
	}
	return nil
}

var File_moneydashboard_v4_transactions_proto protoreflect.FileDescriptor

const file_moneydashboard_v4_transactions_proto_rawDesc = "" +
	"\n" +
	"$moneydashboard/v4/transactions.proto\x12\x11moneydashboard.v4\x1a\"moneydashboard/v4/categories.proto\x1a moneydashboard/v4/holdings.proto\"\xe3\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x03R\x04date\x12\x1f\n" +
	"\vbudget_date\x18\x03 \x01(\x03R\n" +
	"budgetDate\x12#\n" +
	"\rcreation_date\x18\x04 \x01(\x03R\fcreationDate\x12\x14\n" +
	"\x05payee\x18\x05 \x01(\tR\x05payee\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"unit_value\x18\b \x01(\x01R\tunitValue\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted\x124\n" +
	"\aholding\x18\n" +
	" \x01(\v2\x1a.moneydashboard.v4.HoldingR\aholding\x127\n" +
	"\bcategory\x18\v \x01(\v2\x1b.moneydashboard.v4.CategoryR\bcategory\"+\n" +
	"\x19GetTransactionByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x1aGetTransactionByIdResponse\x12@\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1e.moneydashboard.v4.TransactionR\vtransaction\"q\n" +
	"\x19GetTransactionPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12%\n" +
	"\x0esearch_pattern\x18\x03 \x01(\tR\rsearchPattern\"\xa6\x01\n" +
	"\x1aGetTransactionPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12%\n" +
	"\x0efiltered_total\x18\x02 \x01(\x05R\rfilteredTotal\x12K\n" +
	"\x11filtered_entities\x18\x03 \x03(\v2\x1e.moneydashboard.v4.TransactionR\x10filteredEntities\"\\\n" +
	"\x18UpsertTransactionRequest\x12@\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1e.moneydashboard.v4.TransactionR\vtransaction\"\x1b\n" +
	"\x19UpsertTransactionResponse\"*\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteTransactionResponse\"\x12\n" +
	"\x10GetPayeesRequest\"+\n" +
	"\x11GetPayeesResponse\x12\x16\n" +
	"\x06payees\x18\x01 \x03(\tR\x06payees2\xb4\x04\n" +
	"\x14MDTransactionService\x12q\n" +
	"\x12GetTransactionById\x12,.moneydashboard.v4.GetTransactionByIdRequest\x1a-.moneydashboard.v4.GetTransactionByIdResponse\x12q\n" +
	"\x12GetTransactionPage\x12,.moneydashboard.v4.GetTransactionPageRequest\x1a-.moneydashboard.v4.GetTransactionPageResponse\x12n\n" +
	"\x11UpsertTransaction\x12+.moneydashboard.v4.UpsertTransactionRequest\x1a,.moneydashboard.v4.UpsertTransactionResponse\x12n\n" +
	"\x11DeleteTransaction\x12+.moneydashboard.v4.DeleteTransactionRequest\x1a,.moneydashboard.v4.DeleteTransactionResponse\x12V\n" +
	"\tGetPayees\x12#.moneydashboard.v4.GetPayeesRequest\x1a$.moneydashboard.v4.GetPayeesResponseBQZOgithub.com/markormesher/money-dashboard/internal/api_gen/moneydashboard/v4;mdv4b\x06proto3"

var (
	file_moneydashboard_v4_transactions_proto_rawDescOnce sync.Once
	file_moneydashboard_v4_transactions_proto_rawDescData []byte
)

func file_moneydashboard_v4_transactions_proto_rawDescGZIP() []byte {
	file_moneydashboard_v4_transactions_proto_rawDescOnce.Do(func() {
		file_moneydashboard_v4_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_transactions_proto_rawDesc), len(file_moneydashboard_v4_transactions_proto_rawDesc)))
	})
	return file_moneydashboard_v4_transactions_proto_rawDescData
}

var file_moneydashboard_v4_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_moneydashboard_v4_transactions_proto_goTypes = []any{
	(*Transaction)(nil),                // 0: moneydashboard.v4.Transaction
	(*GetTransactionByIdRequest)(nil),  // 1: moneydashboard.v4.GetTransactionByIdRequest
	(*GetTransactionByIdResponse)(nil), // 2: moneydashboard.v4.GetTransactionByIdResponse
	(*GetTransactionPageRequest)(nil),  // 3: moneydashboard.v4.GetTransactionPageRequest
	(*GetTransactionPageResponse)(nil), // 4: moneydashboard.v4.GetTransactionPageResponse
	(*UpsertTransactionRequest)(nil),   // 5: moneydashboard.v4.UpsertTransactionRequest
	(*UpsertTransactionResponse)(nil),  // 6: moneydashboard.v4.UpsertTransactionResponse
	(*DeleteTransactionRequest)(nil),   // 7: moneydashboard.v4.DeleteTransactionRequest
	(*DeleteTransactionResponse)(nil),  // 8: moneydashboard.v4.DeleteTransactionResponse
	(*GetPayeesRequest)(nil),           // 9: moneydashboard.v4.GetPayeesRequest
	(*GetPayeesResponse)(nil),          // 10: moneydashboard.v4.GetPayeesResponse
	(*Holding)(nil),                    // 11: moneydashboard.v4.Holding
	(*Category)(nil),                   // 12: moneydashboard.v4.Category
}
var file_moneydashboard_v4_transactions_proto_depIdxs = []int32{
	11, // 0: moneydashboard.v4.Transaction.holding:type_name -> moneydashboard.v4.Holding
	12, // 1: moneydashboard.v4.Transaction.category:type_name -> moneydashboard.v4.Category
	0,  // 2: moneydashboard.v4.GetTransactionByIdResponse.transaction:type_name -> moneydashboard.v4.Transaction
	0,  // 3: moneydashboard.v4.GetTransactionPageResponse.filtered_entities:type_name -> moneydashboard.v4.Transaction
	0,  // 4: moneydashboard.v4.UpsertTransactionRequest.transaction:type_name -> moneydashboard.v4.Transaction
	1,  // 5: moneydashboard.v4.MDTransactionService.GetTransactionById:input_type -> moneydashboard.v4.GetTransactionByIdRequest
	3,  // 6: moneydashboard.v4.MDTransactionService.GetTransactionPage:input_type -> moneydashboard.v4.GetTransactionPageRequest
	5,  // 7: moneydashboard.v4.MDTransactionService.UpsertTransaction:input_type -> moneydashboard.v4.UpsertTransactionRequest
	7,  // 8: moneydashboard.v4.MDTransactionService.DeleteTransaction:input_type -> moneydashboard.v4.DeleteTransactionRequest
	9,  // 9: moneydashboard.v4.MDTransactionService.GetPayees:input_type -> moneydashboard.v4.GetPayeesRequest
	2,  // 10: moneydashboard.v4.MDTransactionService.GetTransactionById:output_type -> moneydashboard.v4.GetTransactionByIdResponse
	4,  // 11: moneydashboard.v4.MDTransactionService.GetTransactionPage:output_type -> moneydashboard.v4.GetTransactionPageResponse
	6,  // 12: moneydashboard.v4.MDTransactionService.UpsertTransaction:output_type -> moneydashboard.v4.UpsertTransactionResponse
	8,  // 13: moneydashboard.v4.MDTransactionService.DeleteTransaction:output_type -> moneydashboard.v4.DeleteTransactionResponse
	10, // 14: moneydashboard.v4.MDTransactionService.GetPayees:output_type -> moneydashboard.v4.GetPayeesResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_moneydashboard_v4_transactions_proto_init() }
func file_moneydashboard_v4_transactions_proto_init() {
	if File_moneydashboard_v4_transactions_proto != nil {
		return
	}
	file_moneydashboard_v4_categories_proto_init()
	file_moneydashboard_v4_holdings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moneydashboard_v4_transactions_proto_rawDesc), len(file_moneydashboard_v4_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moneydashboard_v4_transactions_proto_goTypes,
		DependencyIndexes: file_moneydashboard_v4_transactions_proto_depIdxs,
		MessageInfos:      file_moneydashboard_v4_transactions_proto_msgTypes,
	}.Build()
	File_moneydashboard_v4_transactions_proto = out.File
	file_moneydashboard_v4_transactions_proto_goTypes = nil
	file_moneydashboard_v4_transactions_proto_depIdxs = nil
}
