// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database_gen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID               pgtype.UUID
	DisplayName      string
	Image            string
	Deleted          bool
	ActiveProfileID  pgtype.UUID
	ExternalUsername pgtype.Text
}

type Usr struct {
	ID               pgtype.UUID
	ExternalUsername string
	DisplayName      string
	Deleted          bool
}
