// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package database_gen

import (
	"context"

	"github.com/google/uuid"
)

const getAllProfiles = `-- name: GetAllProfiles :many
SELECT id, name, deleted FROM profile
WHERE
  profile.id IN (SELECT profile_id FROM user_profile_role WHERE user_id = $1)
  AND
  profile.deleted = FALSE
`

func (q *Queries) GetAllProfiles(ctx context.Context, userID uuid.UUID) ([]Profile, error) {
	rows, err := q.db.Query(ctx, getAllProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(&i.ID, &i.Name, &i.Deleted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileById = `-- name: GetProfileById :one
SELECT id, name, deleted FROM profile
WHERE
  profile.id = $1
  AND
  profile.id IN (SELECT profile_id FROM user_profile_role WHERE user_id = $2)
  AND
  profile.deleted = FALSE
`

type GetProfileByIdParams struct {
	ProfileID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetProfileById(ctx context.Context, arg GetProfileByIdParams) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileById, arg.ProfileID, arg.UserID)
	var i Profile
	err := row.Scan(&i.ID, &i.Name, &i.Deleted)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profile (
  id, name
) VALUES (
  $1, $2
) ON CONFLICT (id) DO UPDATE SET
  name = $2
`

type UpsertProfileParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile, arg.ID, arg.Name)
	return err
}

const upsertUserProfileRole = `-- name: UpsertUserProfileRole :exec
INSERT INTO user_profile_role (
  user_id, profile_id, role
) VALUES (
  $1, $2, $3
) ON CONFLICT (user_id, profile_id) DO UPDATE SET
  role = $3
`

type UpsertUserProfileRoleParams struct {
	UserID    uuid.UUID
	ProfileID uuid.UUID
	Role      string
}

func (q *Queries) UpsertUserProfileRole(ctx context.Context, arg UpsertUserProfileRoleParams) error {
	_, err := q.db.Exec(ctx, upsertUserProfileRole, arg.UserID, arg.ProfileID, arg.Role)
	return err
}
