FROM docker.io/golang:1.26.3@sha256:2d6c80227255c3112a4d08e67ba98e58efd3846daf15d9d7d4c389565d881b1a
WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY ./backend/go.mod ./backend/go.sum ./backend/
RUN cd backend && go mod download

CMD ["bash", "-c", "cd backend ; air --build.cmd 'go build -o ./build/main ./cmd' --build.bin './build/main'"]
