FROM docker.io/golang:1.27.1@sha256:512690a5660563b57d37ecc31129e7f136e831db2aed24a1dbeb8ad7380dc0fa
WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY ./backend/go.mod ./backend/go.sum ./backend/
RUN cd backend && go mod download

CMD ["bash", "-c", "cd backend ; air --build.cmd 'go build -o ./build/main ./cmd' --build.bin './build/main'"]
