FROM docker.io/golang:1.26.1@sha256:c42e4d75186af6a44eb4159dcfac758ef1c05a7011a0052fe8a8df016d8e8fb9
WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY ./backend/go.mod ./backend/go.sum ./backend/
RUN cd backend && go mod download

CMD ["bash", "-c", "cd backend ; air --build.cmd 'go build -o ./build/main ./cmd' --build.bin './build/main'"]
