version: "3.3"

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    secrets:
      - open-exchange-rates-token
      - postgres-password
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - OPEN_EXCHANGE_RATES_TOKEN_FILE=/run/secrets/open-exchange-rates-token
    volumes:
      - ./logs:/logs

  postgres:
    image: postgres:10.1-alpine
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgrespassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

secrets:
  open-exchange-rates-token:
    file: ./secrets/open-exchange-rates-token.txt
  postgres-password:
    file: ./secrets/postgres-password.txt
