version: "3.3"

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    restart: always
    networks:
      - traefik
      - internal
    depends_on:
      - api
    environment:
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
    volumes:
      - ./logs:/app/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.money-dashboard-client.rule=Host(`money-dashboard.tatsu.casa`, `www.money-dashboard.tatsu.casa`)
      - traefik.http.routers.money-dashboard-client.tls.certresolver=letsencrypt
      - traefik.http.routers.money-dashboard-client.middlewares=strip-www@file,authelia@file

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    networks:
      - traefik
      - internal
    depends_on:
      - postgres_primary
    secrets:
      - cron.secret
      - open-exchange-rates.key
      - postgres.password
    environment:
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
      - RUNNING_IN=docker
    volumes:
      - ./logs:/app/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.money-dashboard-api.rule=Host(`money-dashboard.tatsu.casa`, `www.money-dashboard.tatsu.casa`) && PathPrefix(`/api`)
      - traefik.http.routers.money-dashboard-api.tls.certresolver=letsencrypt
      - traefik.http.routers.money-dashboard-api.middlewares=strip-www@file,authelia@file

  cron:
    build: ./docker/cron
    restart: always
    networks:
      - internal
    depends_on:
      - api
    secrets:
      - cron.secret

  postgres_primary:
    image: postgres:10.1-alpine
    restart: always
    networks:
      - internal
    secrets:
      - postgres.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data

volumes:
  postgres-primary-data:

secrets:
  cron.secret:
    file: ./src/api/config/secrets/cron.secret
  open-exchange-rates.key:
    file: ./src/api/config/secrets/open-exchange-rates.key
  postgres.password:
    file: ./src/api/config/secrets/postgres.password

networks:
  internal:
    external: false
  traefik:
    external:
      name: traefik_default
