version: '3.3'

services:
  app:
    build:
      args:
        - BUILD_TYPE=test
    restart: "no"
    secrets:
      - test.secret
    volumes:
      - ./coverage:/app/coverage
    command: yarn start-test

  postgres_master:
    environment:
      - POSTGRES_DATABASE=money_dashboard_test

  postgres_slave_1:
    environment:
      - POSTGRES_DATABASE=money_dashboard_test

  postgres_slave_2:
    environment:
      - POSTGRES_DATABASE=money_dashboard_test

secrets:
  google.client.id:
    file: null
    external: true
  google.client.secret:
    file: null
    external: true
  postgres.password:
    file: null
    external: true
  postgres-rep.password:
    file: null
    external: true
  session.secret:
    file: null
    external: true
  test.secret:
    file: null
    external: true
