version: '3.3'

services:
  app:
    build:
      context: .
      args:
        - NPM_FONT_AWESOME_TOKEN=${NPM_FONT_AWESOME_TOKEN}
    depends_on:
      - postgres
      - redis
    restart: always
    secrets:
      - google.client.id
      - google.client.secret
      - postgres.password
      - session.secret
    environment:
      - ENV=prod
      - NODE_ENV=production
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
      - RUNNING_IN=docker
      - NPM_FONT_AWESOME_TOKEN=${NPM_FONT_AWESOME_TOKEN}
    ports:
      - "3006:3000"

  postgres:
    image: postgres:10.1-alpine
    restart: always
    secrets:
      - postgres.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    restart: always

volumes:
  postgres-data:

secrets:
  google.client.id:
    file: ./src/server/config/secrets/google.client.id
  google.client.secret:
    file: ./src/server/config/secrets/google.client.secret
  postgres.password:
    file: ./src/server/config/secrets/postgres.password
  session.secret:
    file: ./src/server/config/secrets/session.secret
