version: "3.3"

# Note: this compose file is intended for development use only, not as a strict guide for production deployment

services:
  app:
    build:
      context: .
      args:
        - BUILD_TYPE=development
    command: yarn start-dev
    depends_on:
      - postgres
    ports:
      - 3030:3000
    secrets:
      - open-exchange-rates-token
      - polygon-api-token
      - postgres-password
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - OPEN_EXCHANGE_RATES_TOKEN_FILE=/run/secrets/open-exchange-rates-token
      - POLYGON_TOKEN_FILE=/run/secrets/polygon-api-token
    volumes:
      - ./src:/money-dashboard/src
      - ./logs:/logs

  postgres:
    image: postgres:16
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

secrets:
  open-exchange-rates-token:
    file: ./secrets/open-exchange-rates-token.txt
  polygon-api-token:
    file: ./secrets/polygon-api-token.txt
  postgres-password:
    file: ./secrets/postgres-password.txt
