version: "3.3"

services:
  app:
    build:
      context: .
    restart: always
    networks:
      - traefik
      - internal
    depends_on:
      - postgres_primary
    secrets:
      - open-exchange-rates-token
      - postgres-password
    environment:
      - POSTGRES_HOST=postgres_primary
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - OPEN_EXCHANGE_RATES_TOKEN_FILE=/run/secrets/open-exchange-rates-token
    volumes:
      - ./logs:/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.money-dashboard.rule=Host(`money-dashboard.tatsu.casa`, `www.money-dashboard.tatsu.casa`)
      - traefik.http.routers.money-dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.money-dashboard.middlewares=strip-www@file,authelia@file

  postgres_primary:
    image: postgres:10.1-alpine
    restart: always
    networks:
      - internal
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgrespassword
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data

volumes:
  postgres-primary-data:

secrets:
  open-exchange-rates-token:
    file: ./secrets/open-exchange-rates-token.txt
  postgres-password:
    file: ./secrets/postgres-password.txt

networks:
  internal:
    external: false
  traefik:
    external:
      name: traefik_default
