version: '3.3'

services:
  app:
    build: ./app
    depends_on:
      - postgres
    restart: always
    secrets:
      - google.client.id
      - google.client.secret
      - postgres.password
      - session.secret
    environment:
      - ENV=dev
    ports:
      - "3006:3000"
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--timeout=30", "--strict", "--", "node", "./dist/app.js"]

  postgres:
    image: postgres:10.1-alpine
    restart: always
    secrets:
      - postgres.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

secrets:
  google.client.id:
    file: ./secrets/google.client.id
  google.client.secret:
    file: ./secrets/google.client.secret
  postgres.password:
    file: ./secrets/postgres.password
  session.secret:
    file: ./secrets/session.secret
