version: '3.3'

services:
  app:
    environment:
      - ENV=dev
      - NODE_ENV=development
    volumes:
      - ./logs:/usr/src/app/logs

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
