version: '3.3'

services:
  nginx:
    build: ./docker/nginx
    restart: always
    depends_on:
      - api
      - client
    ports:
      - "3006:3006"

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    restart: always
    depends_on:
      - api
    environment:
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
    volumes:
      - ./logs:/app/logs

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    depends_on:
      - redis
      - postgres_primary
      - postgres_replica_1
      - postgres_replica_2
    secrets:
      - google.client.id
      - google.client.secret
      - open-exchange-rates.key
      - postgres.password
      - session.secret
    environment:
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
      - RUNNING_IN=docker
      - IS_PRIMARY_SERVER=yes
    volumes:
      - ./logs:/app/logs

  postgres_primary:
    build: ./docker/postgres-primary
    restart: always
    secrets:
      - postgres.password
      - postgres-rep.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
      - POSTGRES_REP_USER=money_dashboard_rep
      - POSTGRES_REP_PASSWORD_FILE=/run/secrets/postgres-rep.password
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data

  postgres_replica_1:
    build: ./docker/postgres-replica
    restart: always
    secrets:
      - postgres.password
      - postgres-rep.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
      - POSTGRES_REP_USER=money_dashboard_rep
      - POSTGRES_REP_PASSWORD_FILE=/run/secrets/postgres-rep.password
    volumes:
      - postgres-replica-1-data:/var/lib/postgresql/data

  postgres_replica_2:
    build: ./docker/postgres-replica
    restart: always
    secrets:
      - postgres.password
      - postgres-rep.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
      - POSTGRES_REP_USER=money_dashboard_rep
      - POSTGRES_REP_PASSWORD_FILE=/run/secrets/postgres-rep.password
    volumes:
      - postgres-replica-2-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  postgres-primary-data:
  postgres-replica-1-data:
  postgres-replica-2-data:
  redis-data:

secrets:
  google.client.id:
    file: ./src/api/config/secrets/google.client.id
  google.client.secret:
    file: ./src/api/config/secrets/google.client.secret
  open-exchange-rates.key:
    file: ./src/api/config/secrets/open-exchange-rates.key
  postgres.password:
    file: ./src/api/config/secrets/postgres.password
  postgres-rep.password:
    file: ./src/api/config/secrets/postgres-rep.password
  session.secret:
    file: ./src/api/config/secrets/session.secret
