version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - NPM_FONT_AWESOME_TOKEN=${NPM_FONT_AWESOME_TOKEN}
    restart: always
    depends_on:
      - redis
      - postgres_master
      - postgres_slave_1
      - postgres_slave_2
    secrets:
      - google.client.id
      - google.client.secret
      - postgres.password
      - session.secret
    environment:
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
      - RUNNING_IN=docker
      - NPM_FONT_AWESOME_TOKEN=${NPM_FONT_AWESOME_TOKEN}
    volumes:
      - ./logs:/app/logs
    ports:
      - "3006:3006"

  postgres_master:
    build: docker/postgres-master
    restart: always
    secrets:
      - postgres.password
      - postgres-rep.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
      - POSTGRES_REP_USER=money_dashboard_rep
      - POSTGRES_REP_PASSWORD_FILE=/run/secrets/postgres-rep.password
    volumes:
      - postgres-master-data:/var/lib/postgresql/data

  postgres_slave_1:
    build: ./docker/postgres-slave
    restart: always
    secrets:
      - postgres.password
      - postgres-rep.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_USER=money_dashboard
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
      - POSTGRES_REP_USER=money_dashboard_rep
      - POSTGRES_REP_PASSWORD_FILE=/run/secrets/postgres-rep.password
    volumes:
      - /var/lib/postgresql/data

  postgres_slave_2:
    build: ./docker/postgres-slave
    restart: always
    secrets:
      - postgres.password
      - postgres-rep.password
    environment:
      - POSTGRES_DATABASE=money_dashboard
      - POSTGRES_REP_USER=money_dashboard_rep
      - POSTGRES_REP_PASSWORD_FILE=/run/secrets/postgres-rep.password
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    restart: always

volumes:
  postgres-master-data:

secrets:
  google.client.id:
    file: ./src/server/config/secrets/google.client.id
  google.client.secret:
    file: ./src/server/config/secrets/google.client.secret
  postgres.password:
    file: ./src/server/config/secrets/postgres.password
  postgres-rep.password:
    file: ./src/server/config/secrets/postgres-rep.password
  session.secret:
    file: ./src/server/config/secrets/session.secret
