version: 3.7

services:
  money-dashboard:
    build:
      context: .
      dockerfile: Containerfile
    restart: always
    environment:
      - "POSTGRES_CONNECTION_STRING=postgresql://money_dashboard:foobar@postgres/money_dashboard"
    ports:
      - "8080:8080"

  postgres:
    image: "docker.io/library/postgres:17.2"
    environment:
      - "POSTGRES_DATABASE=money_dashboard"
      - "POSTGRES_USER=money_dashboard"
      - "POSTGRES_PASSWORD=foobar"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data: {}
