# This file is maintained by Tedium - manual edits will be overwritten!

version: "3"
includes:
  local:
    taskfile: taskfile.local.yml
    optional: true
tasks:
  cachekey:
    cmds:
      - task: cachekey-backend-go
      - task: cachekey-frontend-js
  cachekey-backend:
    cmds:
      - task: cachekey-backend-go
  cachekey-backend-go:
    dir: '{{.ROOT_DIR}}/backend'
    generates:
      - .task-meta-cache-key
    cmds:
      - cmd: |-
          if [[ -n ${CI:-} ]]; then
            if [[ -n ${FORGEJO_REPOSITORY:-} ]]; then
              PROJECT=$(echo "$FORGEJO_REPOSITORY" | tr -dc '[[a-z0-9]]')
            elif [[ -n ${GITHUB_REPOSITORY:-} ]]; then
              PROJECT=$(echo "$GITHUB_REPOSITORY" | tr -dc '[[a-z0-9]]')
            else
              PROJECT="noproject"
            fi

            DEPS_SHA=$(cat go.mod | sha256sum | awk '{ print $1 }')

            if [[ -f go.sum ]]; then
              LOCK_SHA=$(cat go.sum | sha256sum | awk '{ print $1 }')
            else
              LOCK_SHA="nolock"
            fi

            echo "${PROJECT}-go-v1/${DEPS_SHA}/${LOCK_SHA}" > .task-meta-cache-key
          fi
  cachekey-frontend:
    cmds:
      - task: cachekey-frontend-js
  cachekey-frontend-js:
    dir: '{{.ROOT_DIR}}/frontend'
    generates:
      - .task-meta-cache-key
    cmds:
      - cmd: |-
          if [[ -n ${CI:-} ]]; then
            if [[ -n ${FORGEJO_REPOSITORY:-} ]]; then
              PROJECT=$(echo "$FORGEJO_REPOSITORY" | tr -dc '[[a-z0-9]]')
            elif [[ -n ${GITHUB_REPOSITORY:-} ]]; then
              PROJECT=$(echo "$GITHUB_REPOSITORY" | tr -dc '[[a-z0-9]]')
            else
              PROJECT="noproject"
            fi

            DEPS_SHA=$(cat package.json | sha256sum | awk '{ print $1 }')

            if [[ -f pnpm-lock.yaml ]]; then
              LOCK_SHA=$(cat pnpm-lock.yaml | sha256sum | awk '{ print $1 }')
            elif [[ -f yarn.lock ]]; then
              LOCK_SHA=$(cat yarn.lock | sha256sum | awk '{ print $1 }')
            else
              LOCK_SHA="nolock"
            fi

            echo "${PROJECT}-js-v1/${DEPS_SHA}/${LOCK_SHA}" > .task-meta-cache-key
          fi
  cacheload:
    cmds:
      - task: cacheload-backend-go
      - task: cacheload-frontend-js
  cacheload-backend:
    cmds:
      - task: cacheload-backend-go
  cacheload-backend-go:
    dir: '{{.ROOT_DIR}}/backend'
    deps:
      - cachekey-backend-go
    cmds:
      - cmd: |-
          if [[ -n "${CI_CACHE_TOKEN:-}" ]] && [[ -f ".task-meta-cache-key" ]]; then
            request_key=$(cat ".task-meta-cache-key" | tr -d '\r\n')
            start_ts=$(date +%s)
            header_file=$(mktemp)
            cache_file=$(mktemp)

            echo "loading cache..."
            echo "request key: ${request_key}"
            if curl -fsSL -D "${header_file}" -H "authorization: Bearer ${CI_CACHE_TOKEN}" "https://ci-cache.markormesher.co.uk/cache/${request_key}" -o "${cache_file}"; then
              actual_key=$(cat "${header_file}" | grep -i x-cache-key | cut -d ' ' -f 2 | tr -d '\r\n')
              size=$(du -h "${cache_file}" | awk '{ print $1 }')
              echo "received key: ${actual_key}"
              echo "received size: ${size}"

              if [[ "${actual_key}" == "${request_key}" ]]; then
                touch .task-meta-cache-exact-match
              fi

              echo "unpacking cache..."
              tar xzP -f "${cache_file}" || true
            else
              echo "no cache loaded"
            fi

            rm -f "${cache_file}" "${header_file}"
            end_ts=$(date +%s)
            echo "loading cache took $(( $end_ts - $start_ts ))s"
          fi
  cacheload-frontend:
    cmds:
      - task: cacheload-frontend-js
  cacheload-frontend-js:
    dir: '{{.ROOT_DIR}}/frontend'
    deps:
      - cachekey-frontend-js
    cmds:
      - cmd: |-
          if [[ -n "${CI_CACHE_TOKEN:-}" ]] && [[ -f ".task-meta-cache-key" ]]; then
            request_key=$(cat ".task-meta-cache-key" | tr -d '\r\n')
            start_ts=$(date +%s)
            header_file=$(mktemp)
            cache_file=$(mktemp)

            echo "loading cache..."
            echo "request key: ${request_key}"
            if curl -fsSL -D "${header_file}" -H "authorization: Bearer ${CI_CACHE_TOKEN}" "https://ci-cache.markormesher.co.uk/cache/${request_key}" -o "${cache_file}"; then
              actual_key=$(cat "${header_file}" | grep -i x-cache-key | cut -d ' ' -f 2 | tr -d '\r\n')
              size=$(du -h "${cache_file}" | awk '{ print $1 }')
              echo "received key: ${actual_key}"
              echo "received size: ${size}"

              if [[ "${actual_key}" == "${request_key}" ]]; then
                touch .task-meta-cache-exact-match
              fi

              echo "unpacking cache..."
              tar xzP -f "${cache_file}" || true
            else
              echo "no cache loaded"
            fi

            rm -f "${cache_file}" "${header_file}"
            end_ts=$(date +%s)
            echo "loading cache took $(( $end_ts - $start_ts ))s"
          fi
  cachesave:
    cmds:
      - task: cachesave-backend-go
      - task: cachesave-frontend-js
  cachesave-backend:
    cmds:
      - task: cachesave-backend-go
  cachesave-backend-go:
    dir: '{{.ROOT_DIR}}/backend'
    deps:
      - cachekey-backend-go
    cmds:
      - cmd: echo "$(go env GOMODCACHE) $(go env GOCACHE)" > .task-meta-cache-paths
      - cmd: |-
          if [[ -n "${CI_CACHE_TOKEN:-}" ]] && [[ -f ".task-meta-cache-key" ]]; then
            if [[ -f .task-meta-cache-exact-match ]]; then
              echo "skipping re-upload because an exact match was returned from the cache"
              exit 0
            fi

            request_key=$(cat ".task-meta-cache-key")
            start_ts=$(date +%s)
            cache_file=$(mktemp)

            echo "packing cache..."
            tar czP -f "${cache_file}" $(cat .task-meta-cache-paths)
            size=$(du -h "${cache_file}" | awk '{ print $1 }')

            echo "uploading cache (${size})..."
            if curl -fsSL -H "authorization: Bearer ${CI_CACHE_TOKEN}" -X PUT "https://ci-cache.markormesher.co.uk/cache/${request_key}" --data-binary "@${cache_file}"; then
              echo "uploaded cache"
            else
              echo "error saving cache"
            fi

            rm -f "${cache_file}"
            end_ts=$(date +%s)
            echo "saving cache took $(( $end_ts - $start_ts ))s"
          fi
  cachesave-frontend:
    cmds:
      - task: cachesave-frontend-js
  cachesave-frontend-js:
    dir: '{{.ROOT_DIR}}/frontend'
    deps:
      - cachekey-frontend-js
    cmds:
      - cmd: pnpm store path > .task-meta-cache-paths
      - cmd: |-
          if [[ -n "${CI_CACHE_TOKEN:-}" ]] && [[ -f ".task-meta-cache-key" ]]; then
            if [[ -f .task-meta-cache-exact-match ]]; then
              echo "skipping re-upload because an exact match was returned from the cache"
              exit 0
            fi

            request_key=$(cat ".task-meta-cache-key")
            start_ts=$(date +%s)
            cache_file=$(mktemp)

            echo "packing cache..."
            tar czP -f "${cache_file}" $(cat .task-meta-cache-paths)
            size=$(du -h "${cache_file}" | awk '{ print $1 }')

            echo "uploading cache (${size})..."
            if curl -fsSL -H "authorization: Bearer ${CI_CACHE_TOKEN}" -X PUT "https://ci-cache.markormesher.co.uk/cache/${request_key}" --data-binary "@${cache_file}"; then
              echo "uploaded cache"
            else
              echo "error saving cache"
            fi

            rm -f "${cache_file}"
            end_ts=$(date +%s)
            echo "saving cache took $(( $end_ts - $start_ts ))s"
          fi
  deps:
    cmds:
      - task: deps-backend-go
      - task: deps-frontend-js
  deps-backend:
    cmds:
      - task: deps-backend-go
  deps-backend-go:
    dir: '{{.ROOT_DIR}}/backend'
    cmds:
      - cmd: go mod download
  deps-frontend:
    cmds:
      - task: deps-frontend-js
  deps-frontend-js:
    dir: '{{.ROOT_DIR}}/frontend'
    cmds:
      - cmd: pnpm install --frozen-lockfile
      - cmd: pnpm peers check
  gen:
    cmds:
      - task: gen-backend-goverter
      - task: gen-proto-buf
      - task: gen-sql-sqlc
  gen-backend:
    cmds:
      - task: gen-backend-goverter
  gen-backend-goverter:
    dir: '{{.ROOT_DIR}}/backend'
    cmds:
      - cmd: go tool github.com/jmattheis/goverter/cmd/goverter gen "./internal/api/conversion" "./internal/database/conversion"
  gen-proto:
    cmds:
      - task: gen-proto-buf
  gen-proto-buf:
    dir: '{{.ROOT_DIR}}/proto'
    cmds:
      - cmd: buf generate
  gen-sql:
    cmds:
      - task: gen-sql-sqlc
  gen-sql-sqlc:
    dir: '{{.ROOT_DIR}}/sql'
    cmds:
      - cmd: sqlc generate
  imgbuild:
    cmds:
      - task: imgbuild-root
  imgbuild-root:
    dir: '{{.ROOT_DIR}}'
    deps:
      - imgrefs-root
    cmds:
      - cmd: |-
          set -euo pipefail

          if ! command -v buildah >/dev/null 2>&1; then
            echo "Buildah is not available" >&2
            exit 1
          fi

          buildah_opts=()

          if command -v fuse-overlayfs >/dev/null 2>&1; then
            buildah_opts+=("--storage-opt" "overlay.mount_program=$(command -v fuse-overlayfs)")
          fi

          bud_opts=(
            --layers
            -f "Containerfile"
          )

          if [[ -f argfile.conf ]]; then
            bud_opts+=("--build-arg-file" "argfile.conf")
          fi

          # first build to get visible logs
          buildah "${buildah_opts[@]}" bud "${bud_opts[@]}"

          # Second (cached) build to get the image ID
          img=$(buildah "${buildah_opts[@]}" bud "${bud_opts[@]}" -q)

          if [[ -f .task-meta-imgrefs ]]; then
            cat .task-meta-imgrefs | while read tag; do
              buildah "${buildah_opts[@]}" tag "$img" "${tag}"
              echo "Tagged ${tag}"
            done
          fi
  imgpush:
    cmds:
      - task: imgpush-root
  imgpush-root:
    dir: '{{.ROOT_DIR}}'
    deps:
      - imgrefs-root
    cmds:
      - cmd: |-
          set -euo pipefail

          if ! command -v buildah >/dev/null 2>&1; then
            echo "Buildah is not available" >&2
            exit 1
          fi

          buildah_opts=()

          if command -v fuse-overlayfs >/dev/null 2>&1; then
            buildah_opts+=("--storage-opt" "overlay.mount_program=$(command -v fuse-overlayfs)")
          fi

          if [[ -f .task-meta-imgrefs ]]; then
            cat .task-meta-imgrefs | (grep -v "^localhost" || :) | while read tag; do
              buildah "${buildah_opts[@]}" push "${tag}"
              echo "Pushed ${tag}"
            done
          else
            echo "No .task-meta-imgrefs file - nothing will be pushed"
            exit 1
          fi
  imgrefs:
    cmds:
      - task: imgrefs-root
  imgrefs-root:
    dir: '{{.ROOT_DIR}}'
    cmds:
      - cmd: |-
          set -euo pipefail

          if [[ -f .task-meta-imgrefs ]] && [[ ${CI+y} == "y" ]]; then
            echo "Skipping re-computing tags"
            exit 0
          fi

          if ! command -v git >/dev/null 2>&1; then
            echo "Cannot find git" >&2
            exit 1
          fi

          if ! git describe --tags >/dev/null 2>&1; then
            echo "No git tags to descibe" >&2
            exit 1
          fi

          if ! grep ".task-meta-*" .gitignore >/dev/null 2>&1; then
            echo ".gitignore must include .task-meta-* to use the image builder tasks" >&2
            exit 1
          fi

          img_name=$( (grep "LABEL image.name=" Containerfile || echo) | tail -n 1 | cut -d '=' -f 2-)
          img_registry=$( (grep "LABEL image.registry=" Containerfile || echo) | tail -n 1 | cut -d '=' -f 2-)

          version=$(git describe --tags)
          is_exact_tag=$(git describe --tags --exact-match >/dev/null 2>&1 && echo y || echo n)
          major_version=$(echo "${version}" | cut -d '.' -f 1)
          latest_version_overall=$(git tag -l | sort -V | tail -n 1)
          latest_version_within_major=$(git tag -l | grep "^${major_version}" | sort -V | tail -n 1)

          echo -n "" > .task-meta-imgrefs

          if [[ ! -z "$img_name" ]]; then
            echo "localhost/${img_name}" >> .task-meta-imgrefs
            echo "localhost/${img_name}:${version}" >> .task-meta-imgrefs

            if [[ ! -z "$img_registry" ]] && [[ ${CI+y} == "y" ]]; then
              echo "${img_registry}/${img_name}:${version}" >> .task-meta-imgrefs

              if [[ "${is_exact_tag}" == "y" ]] && [[ "${version}" == "${latest_version_within_major}" ]]; then
                echo "${img_registry}/${img_name}:${major_version}" >> .task-meta-imgrefs
              fi

              if [[ "${is_exact_tag}" == "y" ]] && [[ "${version}" == "${latest_version_overall}" ]]; then
                echo "${img_registry}/${img_name}:latest" >> .task-meta-imgrefs
              fi
            fi
          else
            echo "Warning: no image name label; image will not be tagged" >&2
          fi

          echo "Image refs:"
          cat .task-meta-imgrefs | grep "." || echo "None"
  lint:
    cmds:
      - task: lint-backend-go
      - task: lint-frontend-js
      - task: lint-proto-buf
  lint-backend:
    cmds:
      - task: lint-backend-go
  lint-backend-go:
    dir: '{{.ROOT_DIR}}/backend'
    cmds:
      - cmd: |-
          exit_code=0

          # gofmt
          result=$(gofmt -e -s -d $(go list -f '{{ "{{.Dir}}" }}' ./... | grep -v /.go/ | grep -v /vendor/))
          if [[ ! -z "$result" ]]; then
            echo "## gofmt:"
            echo "$result"
            exit_code=1
          fi

          # staticcheck
          if grep staticcheck go.mod >/dev/null; then
            result=$(go tool staticcheck -checks inherit,+ST1003,+ST1016 ./... || true)
            if [[ ! -z "$result" ]]; then
              echo "## staticcheck:"
              echo "$result"
              exit_code=1
            fi
          fi

          # errcheck
          if grep errcheck go.mod >/dev/null; then
            result=$(go tool errcheck -ignoregenerated ./... || true)
            if [[ ! -z "$result" ]]; then
              echo "## errcheck:"
              echo "$result"
              exit_code=1
            fi
          fi

          exit $exit_code
  lint-frontend:
    cmds:
      - task: lint-frontend-js
  lint-frontend-js:
    dir: '{{.ROOT_DIR}}/frontend'
    cmds:
      - cmd: pnpm lint
  lint-proto:
    cmds:
      - task: lint-proto-buf
  lint-proto-buf:
    dir: '{{.ROOT_DIR}}/proto'
    cmds:
      - cmd: buf format --diff --exit-code
      - cmd: buf lint
  lintfix:
    cmds:
      - task: lintfix-backend-go
      - task: lintfix-frontend-js
      - task: lintfix-proto-buf
  lintfix-backend:
    cmds:
      - task: lintfix-backend-go
  lintfix-backend-go:
    dir: '{{.ROOT_DIR}}/backend'
    cmds:
      - cmd: gofmt -s -w .
  lintfix-frontend:
    cmds:
      - task: lintfix-frontend-js
  lintfix-frontend-js:
    dir: '{{.ROOT_DIR}}/frontend'
    cmds:
      - cmd: pnpm lintfix
  lintfix-proto:
    cmds:
      - task: lintfix-proto-buf
  lintfix-proto-buf:
    dir: '{{.ROOT_DIR}}/proto'
    cmds:
      - cmd: buf format --write
