// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/account_groups.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/account_groups.proto.
 */
export const file_moneydashboard_v4_account_groups: GenFile = /*@__PURE__*/
  fileDesc("CiZtb25leWRhc2hib2FyZC92NC9hY2NvdW50X2dyb3Vwcy5wcm90bxIRbW9uZXlkYXNoYm9hcmQudjQiPwoMQWNjb3VudEdyb3VwEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSFQoNZGlzcGxheV9vcmRlchgDIAEoBSIoChpHZXRBY2NvdW50R3JvdXBCeUlkUmVxdWVzdBIKCgJpZBgBIAEoCSJVChtHZXRBY2NvdW50R3JvdXBCeUlkUmVzcG9uc2USNgoNYWNjb3VudF9ncm91cBgBIAEoCzIfLm1vbmV5ZGFzaGJvYXJkLnY0LkFjY291bnRHcm91cCIcChpHZXRBbGxBY2NvdW50R3JvdXBzUmVxdWVzdCJWChtHZXRBbGxBY2NvdW50R3JvdXBzUmVzcG9uc2USNwoOYWNjb3VudF9ncm91cHMYASADKAsyHy5tb25leWRhc2hib2FyZC52NC5BY2NvdW50R3JvdXAiUwoZVXBzZXJ0QWNjb3VudEdyb3VwUmVxdWVzdBI2Cg1hY2NvdW50X2dyb3VwGAEgASgLMh8ubW9uZXlkYXNoYm9hcmQudjQuQWNjb3VudEdyb3VwIhwKGlVwc2VydEFjY291bnRHcm91cFJlc3BvbnNlMvYCChVNREFjY291bnRHcm91cFNlcnZpY2USdAoTR2V0QWNjb3VudEdyb3VwQnlJZBItLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEFjY291bnRHcm91cEJ5SWRSZXF1ZXN0Gi4ubW9uZXlkYXNoYm9hcmQudjQuR2V0QWNjb3VudEdyb3VwQnlJZFJlc3BvbnNlEnQKE0dldEFsbEFjY291bnRHcm91cHMSLS5tb25leWRhc2hib2FyZC52NC5HZXRBbGxBY2NvdW50R3JvdXBzUmVxdWVzdBouLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEFsbEFjY291bnRHcm91cHNSZXNwb25zZRJxChJVcHNlcnRBY2NvdW50R3JvdXASLC5tb25leWRhc2hib2FyZC52NC5VcHNlcnRBY2NvdW50R3JvdXBSZXF1ZXN0Gi0ubW9uZXlkYXNoYm9hcmQudjQuVXBzZXJ0QWNjb3VudEdyb3VwUmVzcG9uc2VCUVpPZ2l0aHViLmNvbS9tYXJrb3JtZXNoZXIvbW9uZXktZGFzaGJvYXJkL2ludGVybmFsL2FwaV9nZW4vbW9uZXlkYXNoYm9hcmQvdjQ7bWR2NGIGcHJvdG8z");

/**
 * @generated from message moneydashboard.v4.AccountGroup
 */
export type AccountGroup = Message<"moneydashboard.v4.AccountGroup"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 display_order = 3;
   */
  displayOrder: number;
};

/**
 * Describes the message moneydashboard.v4.AccountGroup.
 * Use `create(AccountGroupSchema)` to create a new message.
 */
export const AccountGroupSchema: GenMessage<AccountGroup> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_account_groups, 0);

/**
 * @generated from message moneydashboard.v4.GetAccountGroupByIdRequest
 */
export type GetAccountGroupByIdRequest = Message<"moneydashboard.v4.GetAccountGroupByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message moneydashboard.v4.GetAccountGroupByIdRequest.
 * Use `create(GetAccountGroupByIdRequestSchema)` to create a new message.
 */
export const GetAccountGroupByIdRequestSchema: GenMessage<GetAccountGroupByIdRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_account_groups, 1);

/**
 * @generated from message moneydashboard.v4.GetAccountGroupByIdResponse
 */
export type GetAccountGroupByIdResponse = Message<"moneydashboard.v4.GetAccountGroupByIdResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.AccountGroup account_group = 1;
   */
  accountGroup?: AccountGroup;
};

/**
 * Describes the message moneydashboard.v4.GetAccountGroupByIdResponse.
 * Use `create(GetAccountGroupByIdResponseSchema)` to create a new message.
 */
export const GetAccountGroupByIdResponseSchema: GenMessage<GetAccountGroupByIdResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_account_groups, 2);

/**
 * @generated from message moneydashboard.v4.GetAllAccountGroupsRequest
 */
export type GetAllAccountGroupsRequest = Message<"moneydashboard.v4.GetAllAccountGroupsRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetAllAccountGroupsRequest.
 * Use `create(GetAllAccountGroupsRequestSchema)` to create a new message.
 */
export const GetAllAccountGroupsRequestSchema: GenMessage<GetAllAccountGroupsRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_account_groups, 3);

/**
 * @generated from message moneydashboard.v4.GetAllAccountGroupsResponse
 */
export type GetAllAccountGroupsResponse = Message<"moneydashboard.v4.GetAllAccountGroupsResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.AccountGroup account_groups = 1;
   */
  accountGroups: AccountGroup[];
};

/**
 * Describes the message moneydashboard.v4.GetAllAccountGroupsResponse.
 * Use `create(GetAllAccountGroupsResponseSchema)` to create a new message.
 */
export const GetAllAccountGroupsResponseSchema: GenMessage<GetAllAccountGroupsResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_account_groups, 4);

/**
 * @generated from message moneydashboard.v4.UpsertAccountGroupRequest
 */
export type UpsertAccountGroupRequest = Message<"moneydashboard.v4.UpsertAccountGroupRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.AccountGroup account_group = 1;
   */
  accountGroup?: AccountGroup;
};

/**
 * Describes the message moneydashboard.v4.UpsertAccountGroupRequest.
 * Use `create(UpsertAccountGroupRequestSchema)` to create a new message.
 */
export const UpsertAccountGroupRequestSchema: GenMessage<UpsertAccountGroupRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_account_groups, 5);

/**
 * @generated from message moneydashboard.v4.UpsertAccountGroupResponse
 */
export type UpsertAccountGroupResponse = Message<"moneydashboard.v4.UpsertAccountGroupResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertAccountGroupResponse.
 * Use `create(UpsertAccountGroupResponseSchema)` to create a new message.
 */
export const UpsertAccountGroupResponseSchema: GenMessage<UpsertAccountGroupResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_account_groups, 6);

/**
 * @generated from service moneydashboard.v4.MDAccountGroupService
 */
export const MDAccountGroupService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDAccountGroupService.GetAccountGroupById
   */
  getAccountGroupById: {
    methodKind: "unary";
    input: typeof GetAccountGroupByIdRequestSchema;
    output: typeof GetAccountGroupByIdResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAccountGroupService.GetAllAccountGroups
   */
  getAllAccountGroups: {
    methodKind: "unary";
    input: typeof GetAllAccountGroupsRequestSchema;
    output: typeof GetAllAccountGroupsResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAccountGroupService.UpsertAccountGroup
   */
  upsertAccountGroup: {
    methodKind: "unary";
    input: typeof UpsertAccountGroupRequestSchema;
    output: typeof UpsertAccountGroupResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_account_groups, 0);

