// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/assets.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Currency } from "./currencies_pb.js";
import { file_moneydashboard_v4_currencies } from "./currencies_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/assets.proto.
 */
export const file_moneydashboard_v4_assets: GenFile = /*@__PURE__*/
  fileDesc("Ch5tb25leWRhc2hib2FyZC92NC9hc3NldHMucHJvdG8SEW1vbmV5ZGFzaGJvYXJkLnY0IqkBCgVBc3NldBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg0KBW5vdGVzGAMgASgJEhkKEWRpc3BsYXlfcHJlY2lzaW9uGAQgASgFEh0KFWNhbGN1bGF0aW9uX3ByZWNpc2lvbhgFIAEoBRIOCgZhY3RpdmUYBiABKAgSLQoIY3VycmVuY3kYByABKAsyGy5tb25leWRhc2hib2FyZC52NC5DdXJyZW5jeSIhChNHZXRBc3NldEJ5SWRSZXF1ZXN0EgoKAmlkGAEgASgJIj8KFEdldEFzc2V0QnlJZFJlc3BvbnNlEicKBWFzc2V0GAEgASgLMhgubW9uZXlkYXNoYm9hcmQudjQuQXNzZXQiFQoTR2V0QWxsQXNzZXRzUmVxdWVzdCJAChRHZXRBbGxBc3NldHNSZXNwb25zZRIoCgZhc3NldHMYASADKAsyGC5tb25leWRhc2hib2FyZC52NC5Bc3NldCI9ChJVcHNlcnRBc3NldFJlcXVlc3QSJwoFYXNzZXQYASABKAsyGC5tb25leWRhc2hib2FyZC52NC5Bc3NldCIVChNVcHNlcnRBc3NldFJlc3BvbnNlMrACCg5NREFzc2V0U2VydmljZRJfCgxHZXRBc3NldEJ5SWQSJi5tb25leWRhc2hib2FyZC52NC5HZXRBc3NldEJ5SWRSZXF1ZXN0GicubW9uZXlkYXNoYm9hcmQudjQuR2V0QXNzZXRCeUlkUmVzcG9uc2USXwoMR2V0QWxsQXNzZXRzEiYubW9uZXlkYXNoYm9hcmQudjQuR2V0QWxsQXNzZXRzUmVxdWVzdBonLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEFsbEFzc2V0c1Jlc3BvbnNlElwKC1Vwc2VydEFzc2V0EiUubW9uZXlkYXNoYm9hcmQudjQuVXBzZXJ0QXNzZXRSZXF1ZXN0GiYubW9uZXlkYXNoYm9hcmQudjQuVXBzZXJ0QXNzZXRSZXNwb25zZUJRWk9naXRodWIuY29tL21hcmtvcm1lc2hlci9tb25leS1kYXNoYm9hcmQvaW50ZXJuYWwvYXBpX2dlbi9tb25leWRhc2hib2FyZC92NDttZHY0YgZwcm90bzM", [file_moneydashboard_v4_currencies]);

/**
 * @generated from message moneydashboard.v4.Asset
 */
export type Asset = Message<"moneydashboard.v4.Asset"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string notes = 3;
   */
  notes: string;

  /**
   * @generated from field: int32 display_precision = 4;
   */
  displayPrecision: number;

  /**
   * @generated from field: int32 calculation_precision = 5;
   */
  calculationPrecision: number;

  /**
   * @generated from field: bool active = 6;
   */
  active: boolean;

  /**
   * @generated from field: moneydashboard.v4.Currency currency = 7;
   */
  currency?: Currency;
};

/**
 * Describes the message moneydashboard.v4.Asset.
 * Use `create(AssetSchema)` to create a new message.
 */
export const AssetSchema: GenMessage<Asset> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 0);

/**
 * @generated from message moneydashboard.v4.GetAssetByIdRequest
 */
export type GetAssetByIdRequest = Message<"moneydashboard.v4.GetAssetByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message moneydashboard.v4.GetAssetByIdRequest.
 * Use `create(GetAssetByIdRequestSchema)` to create a new message.
 */
export const GetAssetByIdRequestSchema: GenMessage<GetAssetByIdRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 1);

/**
 * @generated from message moneydashboard.v4.GetAssetByIdResponse
 */
export type GetAssetByIdResponse = Message<"moneydashboard.v4.GetAssetByIdResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.Asset asset = 1;
   */
  asset?: Asset;
};

/**
 * Describes the message moneydashboard.v4.GetAssetByIdResponse.
 * Use `create(GetAssetByIdResponseSchema)` to create a new message.
 */
export const GetAssetByIdResponseSchema: GenMessage<GetAssetByIdResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 2);

/**
 * @generated from message moneydashboard.v4.GetAllAssetsRequest
 */
export type GetAllAssetsRequest = Message<"moneydashboard.v4.GetAllAssetsRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetAllAssetsRequest.
 * Use `create(GetAllAssetsRequestSchema)` to create a new message.
 */
export const GetAllAssetsRequestSchema: GenMessage<GetAllAssetsRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 3);

/**
 * @generated from message moneydashboard.v4.GetAllAssetsResponse
 */
export type GetAllAssetsResponse = Message<"moneydashboard.v4.GetAllAssetsResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.Asset assets = 1;
   */
  assets: Asset[];
};

/**
 * Describes the message moneydashboard.v4.GetAllAssetsResponse.
 * Use `create(GetAllAssetsResponseSchema)` to create a new message.
 */
export const GetAllAssetsResponseSchema: GenMessage<GetAllAssetsResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 4);

/**
 * @generated from message moneydashboard.v4.UpsertAssetRequest
 */
export type UpsertAssetRequest = Message<"moneydashboard.v4.UpsertAssetRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.Asset asset = 1;
   */
  asset?: Asset;
};

/**
 * Describes the message moneydashboard.v4.UpsertAssetRequest.
 * Use `create(UpsertAssetRequestSchema)` to create a new message.
 */
export const UpsertAssetRequestSchema: GenMessage<UpsertAssetRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 5);

/**
 * @generated from message moneydashboard.v4.UpsertAssetResponse
 */
export type UpsertAssetResponse = Message<"moneydashboard.v4.UpsertAssetResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertAssetResponse.
 * Use `create(UpsertAssetResponseSchema)` to create a new message.
 */
export const UpsertAssetResponseSchema: GenMessage<UpsertAssetResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 6);

/**
 * @generated from service moneydashboard.v4.MDAssetService
 */
export const MDAssetService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.GetAssetById
   */
  getAssetById: {
    methodKind: "unary";
    input: typeof GetAssetByIdRequestSchema;
    output: typeof GetAssetByIdResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.GetAllAssets
   */
  getAllAssets: {
    methodKind: "unary";
    input: typeof GetAllAssetsRequestSchema;
    output: typeof GetAllAssetsResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.UpsertAsset
   */
  upsertAsset: {
    methodKind: "unary";
    input: typeof UpsertAssetRequestSchema;
    output: typeof UpsertAssetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_assets, 0);

