// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/assets.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Currency } from "./currencies_pb.js";
import { file_moneydashboard_v4_currencies } from "./currencies_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/assets.proto.
 */
export const file_moneydashboard_v4_assets: GenFile = /*@__PURE__*/
  fileDesc("Ch5tb25leWRhc2hib2FyZC92NC9hc3NldHMucHJvdG8SEW1vbmV5ZGFzaGJvYXJkLnY0IqkBCgVBc3NldBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg0KBW5vdGVzGAMgASgJEhkKEWRpc3BsYXlfcHJlY2lzaW9uGAQgASgFEh0KFWNhbGN1bGF0aW9uX3ByZWNpc2lvbhgFIAEoBRIOCgZhY3RpdmUYBiABKAgSLQoIY3VycmVuY3kYByABKAsyGy5tb25leWRhc2hib2FyZC52NC5DdXJyZW5jeSJHCgpBc3NldFByaWNlEgoKAmlkGAEgASgJEhAKCGFzc2V0X2lkGAIgASgJEgwKBGRhdGUYAyABKAMSDQoFcHJpY2UYBCABKAEiIQoTR2V0QXNzZXRCeUlkUmVxdWVzdBIKCgJpZBgBIAEoCSI/ChRHZXRBc3NldEJ5SWRSZXNwb25zZRInCgVhc3NldBgBIAEoCzIYLm1vbmV5ZGFzaGJvYXJkLnY0LkFzc2V0IhUKE0dldEFsbEFzc2V0c1JlcXVlc3QiQAoUR2V0QWxsQXNzZXRzUmVzcG9uc2USKAoGYXNzZXRzGAEgAygLMhgubW9uZXlkYXNoYm9hcmQudjQuQXNzZXQiPQoSVXBzZXJ0QXNzZXRSZXF1ZXN0EicKBWFzc2V0GAEgASgLMhgubW9uZXlkYXNoYm9hcmQudjQuQXNzZXQiFQoTVXBzZXJ0QXNzZXRSZXNwb25zZSIdChtHZXRMYXRlc3RBc3NldFByaWNlc1JlcXVlc3QiUwocR2V0TGF0ZXN0QXNzZXRQcmljZXNSZXNwb25zZRIzCgxhc3NldF9wcmljZXMYASADKAsyHS5tb25leWRhc2hib2FyZC52NC5Bc3NldFByaWNlIkcKF1Vwc2VydEFzc2V0UHJpY2VSZXF1ZXN0EiwKBXByaWNlGAEgASgLMh0ubW9uZXlkYXNoYm9hcmQudjQuQXNzZXRQcmljZSIaChhVcHNlcnRBc3NldFByaWNlUmVzcG9uc2UylgQKDk1EQXNzZXRTZXJ2aWNlEl8KDEdldEFzc2V0QnlJZBImLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEFzc2V0QnlJZFJlcXVlc3QaJy5tb25leWRhc2hib2FyZC52NC5HZXRBc3NldEJ5SWRSZXNwb25zZRJfCgxHZXRBbGxBc3NldHMSJi5tb25leWRhc2hib2FyZC52NC5HZXRBbGxBc3NldHNSZXF1ZXN0GicubW9uZXlkYXNoYm9hcmQudjQuR2V0QWxsQXNzZXRzUmVzcG9uc2USXAoLVXBzZXJ0QXNzZXQSJS5tb25leWRhc2hib2FyZC52NC5VcHNlcnRBc3NldFJlcXVlc3QaJi5tb25leWRhc2hib2FyZC52NC5VcHNlcnRBc3NldFJlc3BvbnNlEncKFEdldExhdGVzdEFzc2V0UHJpY2VzEi4ubW9uZXlkYXNoYm9hcmQudjQuR2V0TGF0ZXN0QXNzZXRQcmljZXNSZXF1ZXN0Gi8ubW9uZXlkYXNoYm9hcmQudjQuR2V0TGF0ZXN0QXNzZXRQcmljZXNSZXNwb25zZRJrChBVcHNlcnRBc3NldFByaWNlEioubW9uZXlkYXNoYm9hcmQudjQuVXBzZXJ0QXNzZXRQcmljZVJlcXVlc3QaKy5tb25leWRhc2hib2FyZC52NC5VcHNlcnRBc3NldFByaWNlUmVzcG9uc2VCUVpPZ2l0aHViLmNvbS9tYXJrb3JtZXNoZXIvbW9uZXktZGFzaGJvYXJkL2ludGVybmFsL2FwaV9nZW4vbW9uZXlkYXNoYm9hcmQvdjQ7bWR2NGIGcHJvdG8z", [file_moneydashboard_v4_currencies]);

/**
 * @generated from message moneydashboard.v4.Asset
 */
export type Asset = Message<"moneydashboard.v4.Asset"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string notes = 3;
   */
  notes: string;

  /**
   * @generated from field: int32 display_precision = 4;
   */
  displayPrecision: number;

  /**
   * @generated from field: int32 calculation_precision = 5;
   */
  calculationPrecision: number;

  /**
   * @generated from field: bool active = 6;
   */
  active: boolean;

  /**
   * @generated from field: moneydashboard.v4.Currency currency = 7;
   */
  currency?: Currency;
};

/**
 * Describes the message moneydashboard.v4.Asset.
 * Use `create(AssetSchema)` to create a new message.
 */
export const AssetSchema: GenMessage<Asset> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 0);

/**
 * @generated from message moneydashboard.v4.AssetPrice
 */
export type AssetPrice = Message<"moneydashboard.v4.AssetPrice"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string asset_id = 2;
   */
  assetId: string;

  /**
   * @generated from field: int64 date = 3;
   */
  date: bigint;

  /**
   * @generated from field: double price = 4;
   */
  price: number;
};

/**
 * Describes the message moneydashboard.v4.AssetPrice.
 * Use `create(AssetPriceSchema)` to create a new message.
 */
export const AssetPriceSchema: GenMessage<AssetPrice> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 1);

/**
 * @generated from message moneydashboard.v4.GetAssetByIdRequest
 */
export type GetAssetByIdRequest = Message<"moneydashboard.v4.GetAssetByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message moneydashboard.v4.GetAssetByIdRequest.
 * Use `create(GetAssetByIdRequestSchema)` to create a new message.
 */
export const GetAssetByIdRequestSchema: GenMessage<GetAssetByIdRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 2);

/**
 * @generated from message moneydashboard.v4.GetAssetByIdResponse
 */
export type GetAssetByIdResponse = Message<"moneydashboard.v4.GetAssetByIdResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.Asset asset = 1;
   */
  asset?: Asset;
};

/**
 * Describes the message moneydashboard.v4.GetAssetByIdResponse.
 * Use `create(GetAssetByIdResponseSchema)` to create a new message.
 */
export const GetAssetByIdResponseSchema: GenMessage<GetAssetByIdResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 3);

/**
 * @generated from message moneydashboard.v4.GetAllAssetsRequest
 */
export type GetAllAssetsRequest = Message<"moneydashboard.v4.GetAllAssetsRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetAllAssetsRequest.
 * Use `create(GetAllAssetsRequestSchema)` to create a new message.
 */
export const GetAllAssetsRequestSchema: GenMessage<GetAllAssetsRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 4);

/**
 * @generated from message moneydashboard.v4.GetAllAssetsResponse
 */
export type GetAllAssetsResponse = Message<"moneydashboard.v4.GetAllAssetsResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.Asset assets = 1;
   */
  assets: Asset[];
};

/**
 * Describes the message moneydashboard.v4.GetAllAssetsResponse.
 * Use `create(GetAllAssetsResponseSchema)` to create a new message.
 */
export const GetAllAssetsResponseSchema: GenMessage<GetAllAssetsResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 5);

/**
 * @generated from message moneydashboard.v4.UpsertAssetRequest
 */
export type UpsertAssetRequest = Message<"moneydashboard.v4.UpsertAssetRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.Asset asset = 1;
   */
  asset?: Asset;
};

/**
 * Describes the message moneydashboard.v4.UpsertAssetRequest.
 * Use `create(UpsertAssetRequestSchema)` to create a new message.
 */
export const UpsertAssetRequestSchema: GenMessage<UpsertAssetRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 6);

/**
 * @generated from message moneydashboard.v4.UpsertAssetResponse
 */
export type UpsertAssetResponse = Message<"moneydashboard.v4.UpsertAssetResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertAssetResponse.
 * Use `create(UpsertAssetResponseSchema)` to create a new message.
 */
export const UpsertAssetResponseSchema: GenMessage<UpsertAssetResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 7);

/**
 * @generated from message moneydashboard.v4.GetLatestAssetPricesRequest
 */
export type GetLatestAssetPricesRequest = Message<"moneydashboard.v4.GetLatestAssetPricesRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetLatestAssetPricesRequest.
 * Use `create(GetLatestAssetPricesRequestSchema)` to create a new message.
 */
export const GetLatestAssetPricesRequestSchema: GenMessage<GetLatestAssetPricesRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 8);

/**
 * @generated from message moneydashboard.v4.GetLatestAssetPricesResponse
 */
export type GetLatestAssetPricesResponse = Message<"moneydashboard.v4.GetLatestAssetPricesResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.AssetPrice asset_prices = 1;
   */
  assetPrices: AssetPrice[];
};

/**
 * Describes the message moneydashboard.v4.GetLatestAssetPricesResponse.
 * Use `create(GetLatestAssetPricesResponseSchema)` to create a new message.
 */
export const GetLatestAssetPricesResponseSchema: GenMessage<GetLatestAssetPricesResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 9);

/**
 * @generated from message moneydashboard.v4.UpsertAssetPriceRequest
 */
export type UpsertAssetPriceRequest = Message<"moneydashboard.v4.UpsertAssetPriceRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.AssetPrice price = 1;
   */
  price?: AssetPrice;
};

/**
 * Describes the message moneydashboard.v4.UpsertAssetPriceRequest.
 * Use `create(UpsertAssetPriceRequestSchema)` to create a new message.
 */
export const UpsertAssetPriceRequestSchema: GenMessage<UpsertAssetPriceRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 10);

/**
 * @generated from message moneydashboard.v4.UpsertAssetPriceResponse
 */
export type UpsertAssetPriceResponse = Message<"moneydashboard.v4.UpsertAssetPriceResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertAssetPriceResponse.
 * Use `create(UpsertAssetPriceResponseSchema)` to create a new message.
 */
export const UpsertAssetPriceResponseSchema: GenMessage<UpsertAssetPriceResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_assets, 11);

/**
 * @generated from service moneydashboard.v4.MDAssetService
 */
export const MDAssetService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.GetAssetById
   */
  getAssetById: {
    methodKind: "unary";
    input: typeof GetAssetByIdRequestSchema;
    output: typeof GetAssetByIdResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.GetAllAssets
   */
  getAllAssets: {
    methodKind: "unary";
    input: typeof GetAllAssetsRequestSchema;
    output: typeof GetAllAssetsResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.UpsertAsset
   */
  upsertAsset: {
    methodKind: "unary";
    input: typeof UpsertAssetRequestSchema;
    output: typeof UpsertAssetResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.GetLatestAssetPrices
   */
  getLatestAssetPrices: {
    methodKind: "unary";
    input: typeof GetLatestAssetPricesRequestSchema;
    output: typeof GetLatestAssetPricesResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDAssetService.UpsertAssetPrice
   */
  upsertAssetPrice: {
    methodKind: "unary";
    input: typeof UpsertAssetPriceRequestSchema;
    output: typeof UpsertAssetPriceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_assets, 0);

