// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/categories.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/categories.proto.
 */
export const file_moneydashboard_v4_categories: GenFile = /*@__PURE__*/
  fileDesc("CiJtb25leWRhc2hib2FyZC92NC9jYXRlZ29yaWVzLnByb3RvEhFtb25leWRhc2hib2FyZC52NCL7AQoIQ2F0ZWdvcnkSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIPCgdpc19tZW1vGAMgASgIEhoKEmlzX2ludGVyZXN0X2luY29tZRgEIAEoCBIaChJpc19kaXZpZGVuZF9pbmNvbWUYBSABKAgSHgoWaXNfY2FwaXRhbF9hY3F1aXNpdGlvbhgGIAEoCBIbChNpc19jYXBpdGFsX2Rpc3Bvc2FsGAcgASgIEhwKFGlzX2NhcGl0YWxfZXZlbnRfZmVlGAggASgIEiEKGWlzX3N5bnRoZXRpY19hc3NldF91cGRhdGUYCSABKAgSDgoGYWN0aXZlGAogASgIIiQKFkdldENhdGVnb3J5QnlJZFJlcXVlc3QSCgoCaWQYASABKAkiSAoXR2V0Q2F0ZWdvcnlCeUlkUmVzcG9uc2USLQoIY2F0ZWdvcnkYASABKAsyGy5tb25leWRhc2hib2FyZC52NC5DYXRlZ29yeSIZChdHZXRBbGxDYXRlZ29yaWVzUmVxdWVzdCJLChhHZXRBbGxDYXRlZ29yaWVzUmVzcG9uc2USLwoKY2F0ZWdvcmllcxgBIAMoCzIbLm1vbmV5ZGFzaGJvYXJkLnY0LkNhdGVnb3J5IkYKFVVwc2VydENhdGVnb3J5UmVxdWVzdBItCghjYXRlZ29yeRgBIAEoCzIbLm1vbmV5ZGFzaGJvYXJkLnY0LkNhdGVnb3J5IhgKFlVwc2VydENhdGVnb3J5UmVzcG9uc2Uy0QIKEU1EQ2F0ZWdvcnlTZXJ2aWNlEmgKD0dldENhdGVnb3J5QnlJZBIpLm1vbmV5ZGFzaGJvYXJkLnY0LkdldENhdGVnb3J5QnlJZFJlcXVlc3QaKi5tb25leWRhc2hib2FyZC52NC5HZXRDYXRlZ29yeUJ5SWRSZXNwb25zZRJrChBHZXRBbGxDYXRlZ29yaWVzEioubW9uZXlkYXNoYm9hcmQudjQuR2V0QWxsQ2F0ZWdvcmllc1JlcXVlc3QaKy5tb25leWRhc2hib2FyZC52NC5HZXRBbGxDYXRlZ29yaWVzUmVzcG9uc2USZQoOVXBzZXJ0Q2F0ZWdvcnkSKC5tb25leWRhc2hib2FyZC52NC5VcHNlcnRDYXRlZ29yeVJlcXVlc3QaKS5tb25leWRhc2hib2FyZC52NC5VcHNlcnRDYXRlZ29yeVJlc3BvbnNlQlFaT2dpdGh1Yi5jb20vbWFya29ybWVzaGVyL21vbmV5LWRhc2hib2FyZC9pbnRlcm5hbC9hcGlfZ2VuL21vbmV5ZGFzaGJvYXJkL3Y0O21kdjRiBnByb3RvMw");

/**
 * @generated from message moneydashboard.v4.Category
 */
export type Category = Message<"moneydashboard.v4.Category"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bool is_memo = 3;
   */
  isMemo: boolean;

  /**
   * @generated from field: bool is_interest_income = 4;
   */
  isInterestIncome: boolean;

  /**
   * @generated from field: bool is_dividend_income = 5;
   */
  isDividendIncome: boolean;

  /**
   * @generated from field: bool is_capital_acquisition = 6;
   */
  isCapitalAcquisition: boolean;

  /**
   * @generated from field: bool is_capital_disposal = 7;
   */
  isCapitalDisposal: boolean;

  /**
   * @generated from field: bool is_capital_event_fee = 8;
   */
  isCapitalEventFee: boolean;

  /**
   * @generated from field: bool is_synthetic_asset_update = 9;
   */
  isSyntheticAssetUpdate: boolean;

  /**
   * @generated from field: bool active = 10;
   */
  active: boolean;
};

/**
 * Describes the message moneydashboard.v4.Category.
 * Use `create(CategorySchema)` to create a new message.
 */
export const CategorySchema: GenMessage<Category> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_categories, 0);

/**
 * @generated from message moneydashboard.v4.GetCategoryByIdRequest
 */
export type GetCategoryByIdRequest = Message<"moneydashboard.v4.GetCategoryByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message moneydashboard.v4.GetCategoryByIdRequest.
 * Use `create(GetCategoryByIdRequestSchema)` to create a new message.
 */
export const GetCategoryByIdRequestSchema: GenMessage<GetCategoryByIdRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_categories, 1);

/**
 * @generated from message moneydashboard.v4.GetCategoryByIdResponse
 */
export type GetCategoryByIdResponse = Message<"moneydashboard.v4.GetCategoryByIdResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.Category category = 1;
   */
  category?: Category;
};

/**
 * Describes the message moneydashboard.v4.GetCategoryByIdResponse.
 * Use `create(GetCategoryByIdResponseSchema)` to create a new message.
 */
export const GetCategoryByIdResponseSchema: GenMessage<GetCategoryByIdResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_categories, 2);

/**
 * @generated from message moneydashboard.v4.GetAllCategoriesRequest
 */
export type GetAllCategoriesRequest = Message<"moneydashboard.v4.GetAllCategoriesRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetAllCategoriesRequest.
 * Use `create(GetAllCategoriesRequestSchema)` to create a new message.
 */
export const GetAllCategoriesRequestSchema: GenMessage<GetAllCategoriesRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_categories, 3);

/**
 * @generated from message moneydashboard.v4.GetAllCategoriesResponse
 */
export type GetAllCategoriesResponse = Message<"moneydashboard.v4.GetAllCategoriesResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.Category categories = 1;
   */
  categories: Category[];
};

/**
 * Describes the message moneydashboard.v4.GetAllCategoriesResponse.
 * Use `create(GetAllCategoriesResponseSchema)` to create a new message.
 */
export const GetAllCategoriesResponseSchema: GenMessage<GetAllCategoriesResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_categories, 4);

/**
 * @generated from message moneydashboard.v4.UpsertCategoryRequest
 */
export type UpsertCategoryRequest = Message<"moneydashboard.v4.UpsertCategoryRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.Category category = 1;
   */
  category?: Category;
};

/**
 * Describes the message moneydashboard.v4.UpsertCategoryRequest.
 * Use `create(UpsertCategoryRequestSchema)` to create a new message.
 */
export const UpsertCategoryRequestSchema: GenMessage<UpsertCategoryRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_categories, 5);

/**
 * @generated from message moneydashboard.v4.UpsertCategoryResponse
 */
export type UpsertCategoryResponse = Message<"moneydashboard.v4.UpsertCategoryResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertCategoryResponse.
 * Use `create(UpsertCategoryResponseSchema)` to create a new message.
 */
export const UpsertCategoryResponseSchema: GenMessage<UpsertCategoryResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_categories, 6);

/**
 * @generated from service moneydashboard.v4.MDCategoryService
 */
export const MDCategoryService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDCategoryService.GetCategoryById
   */
  getCategoryById: {
    methodKind: "unary";
    input: typeof GetCategoryByIdRequestSchema;
    output: typeof GetCategoryByIdResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDCategoryService.GetAllCategories
   */
  getAllCategories: {
    methodKind: "unary";
    input: typeof GetAllCategoriesRequestSchema;
    output: typeof GetAllCategoriesResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDCategoryService.UpsertCategory
   */
  upsertCategory: {
    methodKind: "unary";
    input: typeof UpsertCategoryRequestSchema;
    output: typeof UpsertCategoryResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_categories, 0);

