// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/currencies.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/currencies.proto.
 */
export const file_moneydashboard_v4_currencies: GenFile = /*@__PURE__*/
  fileDesc("CiJtb25leWRhc2hib2FyZC92NC9jdXJyZW5jaWVzLnByb3RvEhFtb25leWRhc2hib2FyZC52NCJ+CghDdXJyZW5jeRIKCgJpZBgBIAEoCRIMCgRjb2RlGAIgASgJEg4KBnN5bWJvbBgDIAEoCRIZChFkaXNwbGF5X3ByZWNpc2lvbhgEIAEoBRIdChVjYWxjdWxhdGlvbl9wcmVjaXNpb24YBSABKAUSDgoGYWN0aXZlGAYgASgIIiQKFkdldEN1cnJlbmN5QnlJZFJlcXVlc3QSCgoCaWQYASABKAkiSAoXR2V0Q3VycmVuY3lCeUlkUmVzcG9uc2USLQoIY3VycmVuY3kYASABKAsyGy5tb25leWRhc2hib2FyZC52NC5DdXJyZW5jeSIZChdHZXRBbGxDdXJyZW5jaWVzUmVxdWVzdCJLChhHZXRBbGxDdXJyZW5jaWVzUmVzcG9uc2USLwoKY3VycmVuY2llcxgBIAMoCzIbLm1vbmV5ZGFzaGJvYXJkLnY0LkN1cnJlbmN5IkYKFVVwc2VydEN1cnJlbmN5UmVxdWVzdBItCghjdXJyZW5jeRgBIAEoCzIbLm1vbmV5ZGFzaGJvYXJkLnY0LkN1cnJlbmN5IhgKFlVwc2VydEN1cnJlbmN5UmVzcG9uc2Uy0QIKEU1EQ3VycmVuY3lTZXJ2aWNlEmgKD0dldEN1cnJlbmN5QnlJZBIpLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEN1cnJlbmN5QnlJZFJlcXVlc3QaKi5tb25leWRhc2hib2FyZC52NC5HZXRDdXJyZW5jeUJ5SWRSZXNwb25zZRJrChBHZXRBbGxDdXJyZW5jaWVzEioubW9uZXlkYXNoYm9hcmQudjQuR2V0QWxsQ3VycmVuY2llc1JlcXVlc3QaKy5tb25leWRhc2hib2FyZC52NC5HZXRBbGxDdXJyZW5jaWVzUmVzcG9uc2USZQoOVXBzZXJ0Q3VycmVuY3kSKC5tb25leWRhc2hib2FyZC52NC5VcHNlcnRDdXJyZW5jeVJlcXVlc3QaKS5tb25leWRhc2hib2FyZC52NC5VcHNlcnRDdXJyZW5jeVJlc3BvbnNlQlFaT2dpdGh1Yi5jb20vbWFya29ybWVzaGVyL21vbmV5LWRhc2hib2FyZC9pbnRlcm5hbC9hcGlfZ2VuL21vbmV5ZGFzaGJvYXJkL3Y0O21kdjRiBnByb3RvMw");

/**
 * @generated from message moneydashboard.v4.Currency
 */
export type Currency = Message<"moneydashboard.v4.Currency"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string symbol = 3;
   */
  symbol: string;

  /**
   * @generated from field: int32 display_precision = 4;
   */
  displayPrecision: number;

  /**
   * @generated from field: int32 calculation_precision = 5;
   */
  calculationPrecision: number;

  /**
   * @generated from field: bool active = 6;
   */
  active: boolean;
};

/**
 * Describes the message moneydashboard.v4.Currency.
 * Use `create(CurrencySchema)` to create a new message.
 */
export const CurrencySchema: GenMessage<Currency> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 0);

/**
 * @generated from message moneydashboard.v4.GetCurrencyByIdRequest
 */
export type GetCurrencyByIdRequest = Message<"moneydashboard.v4.GetCurrencyByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message moneydashboard.v4.GetCurrencyByIdRequest.
 * Use `create(GetCurrencyByIdRequestSchema)` to create a new message.
 */
export const GetCurrencyByIdRequestSchema: GenMessage<GetCurrencyByIdRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 1);

/**
 * @generated from message moneydashboard.v4.GetCurrencyByIdResponse
 */
export type GetCurrencyByIdResponse = Message<"moneydashboard.v4.GetCurrencyByIdResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.Currency currency = 1;
   */
  currency?: Currency;
};

/**
 * Describes the message moneydashboard.v4.GetCurrencyByIdResponse.
 * Use `create(GetCurrencyByIdResponseSchema)` to create a new message.
 */
export const GetCurrencyByIdResponseSchema: GenMessage<GetCurrencyByIdResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 2);

/**
 * @generated from message moneydashboard.v4.GetAllCurrenciesRequest
 */
export type GetAllCurrenciesRequest = Message<"moneydashboard.v4.GetAllCurrenciesRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetAllCurrenciesRequest.
 * Use `create(GetAllCurrenciesRequestSchema)` to create a new message.
 */
export const GetAllCurrenciesRequestSchema: GenMessage<GetAllCurrenciesRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 3);

/**
 * @generated from message moneydashboard.v4.GetAllCurrenciesResponse
 */
export type GetAllCurrenciesResponse = Message<"moneydashboard.v4.GetAllCurrenciesResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.Currency currencies = 1;
   */
  currencies: Currency[];
};

/**
 * Describes the message moneydashboard.v4.GetAllCurrenciesResponse.
 * Use `create(GetAllCurrenciesResponseSchema)` to create a new message.
 */
export const GetAllCurrenciesResponseSchema: GenMessage<GetAllCurrenciesResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 4);

/**
 * @generated from message moneydashboard.v4.UpsertCurrencyRequest
 */
export type UpsertCurrencyRequest = Message<"moneydashboard.v4.UpsertCurrencyRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.Currency currency = 1;
   */
  currency?: Currency;
};

/**
 * Describes the message moneydashboard.v4.UpsertCurrencyRequest.
 * Use `create(UpsertCurrencyRequestSchema)` to create a new message.
 */
export const UpsertCurrencyRequestSchema: GenMessage<UpsertCurrencyRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 5);

/**
 * @generated from message moneydashboard.v4.UpsertCurrencyResponse
 */
export type UpsertCurrencyResponse = Message<"moneydashboard.v4.UpsertCurrencyResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertCurrencyResponse.
 * Use `create(UpsertCurrencyResponseSchema)` to create a new message.
 */
export const UpsertCurrencyResponseSchema: GenMessage<UpsertCurrencyResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 6);

/**
 * @generated from service moneydashboard.v4.MDCurrencyService
 */
export const MDCurrencyService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDCurrencyService.GetCurrencyById
   */
  getCurrencyById: {
    methodKind: "unary";
    input: typeof GetCurrencyByIdRequestSchema;
    output: typeof GetCurrencyByIdResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDCurrencyService.GetAllCurrencies
   */
  getAllCurrencies: {
    methodKind: "unary";
    input: typeof GetAllCurrenciesRequestSchema;
    output: typeof GetAllCurrenciesResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDCurrencyService.UpsertCurrency
   */
  upsertCurrency: {
    methodKind: "unary";
    input: typeof UpsertCurrencyRequestSchema;
    output: typeof UpsertCurrencyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_currencies, 0);

