// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file moneydashboard/v4/currencies.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/currencies.proto.
 */
export const file_moneydashboard_v4_currencies: GenFile = /*@__PURE__*/
  fileDesc("CiJtb25leWRhc2hib2FyZC92NC9jdXJyZW5jaWVzLnByb3RvEhFtb25leWRhc2hib2FyZC52NCJcCghDdXJyZW5jeRIKCgJpZBgBIAEoCRIMCgRjb2RlGAIgASgJEg4KBnN5bWJvbBgDIAEoCRIWCg5kZWNpbWFsX3BsYWNlcxgEIAEoBRIOCgZhY3RpdmUYBSABKAgiGQoXR2V0QWxsQ3VycmVuY2llc1JlcXVlc3QiSwoYR2V0QWxsQ3VycmVuY2llc1Jlc3BvbnNlEi8KCmN1cnJlbmNpZXMYASADKAsyGy5tb25leWRhc2hib2FyZC52NC5DdXJyZW5jeUJRWk9naXRodWIuY29tL21hcmtvcm1lc2hlci9tb25leS1kYXNoYm9hcmQvaW50ZXJuYWwvYXBpX2dlbi9tb25leWRhc2hib2FyZC92NDttZHY0YgZwcm90bzM");

/**
 * @generated from message moneydashboard.v4.Currency
 */
export type Currency = Message<"moneydashboard.v4.Currency"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string symbol = 3;
   */
  symbol: string;

  /**
   * @generated from field: int32 decimal_places = 4;
   */
  decimalPlaces: number;

  /**
   * @generated from field: bool active = 5;
   */
  active: boolean;
};

/**
 * Describes the message moneydashboard.v4.Currency.
 * Use `create(CurrencySchema)` to create a new message.
 */
export const CurrencySchema: GenMessage<Currency> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 0);

/**
 * @generated from message moneydashboard.v4.GetAllCurrenciesRequest
 */
export type GetAllCurrenciesRequest = Message<"moneydashboard.v4.GetAllCurrenciesRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetAllCurrenciesRequest.
 * Use `create(GetAllCurrenciesRequestSchema)` to create a new message.
 */
export const GetAllCurrenciesRequestSchema: GenMessage<GetAllCurrenciesRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 1);

/**
 * @generated from message moneydashboard.v4.GetAllCurrenciesResponse
 */
export type GetAllCurrenciesResponse = Message<"moneydashboard.v4.GetAllCurrenciesResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.Currency currencies = 1;
   */
  currencies: Currency[];
};

/**
 * Describes the message moneydashboard.v4.GetAllCurrenciesResponse.
 * Use `create(GetAllCurrenciesResponseSchema)` to create a new message.
 */
export const GetAllCurrenciesResponseSchema: GenMessage<GetAllCurrenciesResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_currencies, 2);

