// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/envelope_allocations.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Category } from "./categories_pb.js";
import { file_moneydashboard_v4_categories } from "./categories_pb.js";
import type { Envelope } from "./envelopes_pb.js";
import { file_moneydashboard_v4_envelopes } from "./envelopes_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/envelope_allocations.proto.
 */
export const file_moneydashboard_v4_envelope_allocations: GenFile = /*@__PURE__*/
  fileDesc("Cixtb25leWRhc2hib2FyZC92NC9lbnZlbG9wZV9hbGxvY2F0aW9ucy5wcm90bxIRbW9uZXlkYXNoYm9hcmQudjQikgEKEkVudmVsb3BlQWxsb2NhdGlvbhIKCgJpZBgBIAEoCRISCgpzdGFydF9kYXRlGAIgASgDEi0KCGNhdGVnb3J5GAMgASgLMhsubW9uZXlkYXNoYm9hcmQudjQuQ2F0ZWdvcnkSLQoIZW52ZWxvcGUYBCABKAsyGy5tb25leWRhc2hib2FyZC52NC5FbnZlbG9wZSIuCiBHZXRFbnZlbG9wZUFsbG9jYXRpb25CeUlkUmVxdWVzdBIKCgJpZBgBIAEoCSJnCiFHZXRFbnZlbG9wZUFsbG9jYXRpb25CeUlkUmVzcG9uc2USQgoTZW52ZWxvcGVfYWxsb2NhdGlvbhgBIAEoCzIlLm1vbmV5ZGFzaGJvYXJkLnY0LkVudmVsb3BlQWxsb2NhdGlvbiIiCiBHZXRBbGxFbnZlbG9wZUFsbG9jYXRpb25zUmVxdWVzdCJoCiFHZXRBbGxFbnZlbG9wZUFsbG9jYXRpb25zUmVzcG9uc2USQwoUZW52ZWxvcGVfYWxsb2NhdGlvbnMYASADKAsyJS5tb25leWRhc2hib2FyZC52NC5FbnZlbG9wZUFsbG9jYXRpb24iZQofVXBzZXJ0RW52ZWxvcGVBbGxvY2F0aW9uUmVxdWVzdBJCChNlbnZlbG9wZV9hbGxvY2F0aW9uGAEgASgLMiUubW9uZXlkYXNoYm9hcmQudjQuRW52ZWxvcGVBbGxvY2F0aW9uIiIKIFVwc2VydEVudmVsb3BlQWxsb2NhdGlvblJlc3BvbnNlMrUDChtNREVudmVsb3BlQWxsb2NhdGlvblNlcnZpY2UShgEKGUdldEVudmVsb3BlQWxsb2NhdGlvbkJ5SWQSMy5tb25leWRhc2hib2FyZC52NC5HZXRFbnZlbG9wZUFsbG9jYXRpb25CeUlkUmVxdWVzdBo0Lm1vbmV5ZGFzaGJvYXJkLnY0LkdldEVudmVsb3BlQWxsb2NhdGlvbkJ5SWRSZXNwb25zZRKGAQoZR2V0QWxsRW52ZWxvcGVBbGxvY2F0aW9ucxIzLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEFsbEVudmVsb3BlQWxsb2NhdGlvbnNSZXF1ZXN0GjQubW9uZXlkYXNoYm9hcmQudjQuR2V0QWxsRW52ZWxvcGVBbGxvY2F0aW9uc1Jlc3BvbnNlEoMBChhVcHNlcnRFbnZlbG9wZUFsbG9jYXRpb24SMi5tb25leWRhc2hib2FyZC52NC5VcHNlcnRFbnZlbG9wZUFsbG9jYXRpb25SZXF1ZXN0GjMubW9uZXlkYXNoYm9hcmQudjQuVXBzZXJ0RW52ZWxvcGVBbGxvY2F0aW9uUmVzcG9uc2VCUVpPZ2l0aHViLmNvbS9tYXJrb3JtZXNoZXIvbW9uZXktZGFzaGJvYXJkL2ludGVybmFsL2FwaV9nZW4vbW9uZXlkYXNoYm9hcmQvdjQ7bWR2NGIGcHJvdG8z", [file_moneydashboard_v4_categories, file_moneydashboard_v4_envelopes]);

/**
 * @generated from message moneydashboard.v4.EnvelopeAllocation
 */
export type EnvelopeAllocation = Message<"moneydashboard.v4.EnvelopeAllocation"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 start_date = 2;
   */
  startDate: bigint;

  /**
   * @generated from field: moneydashboard.v4.Category category = 3;
   */
  category?: Category;

  /**
   * @generated from field: moneydashboard.v4.Envelope envelope = 4;
   */
  envelope?: Envelope;
};

/**
 * Describes the message moneydashboard.v4.EnvelopeAllocation.
 * Use `create(EnvelopeAllocationSchema)` to create a new message.
 */
export const EnvelopeAllocationSchema: GenMessage<EnvelopeAllocation> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_envelope_allocations, 0);

/**
 * @generated from message moneydashboard.v4.GetEnvelopeAllocationByIdRequest
 */
export type GetEnvelopeAllocationByIdRequest = Message<"moneydashboard.v4.GetEnvelopeAllocationByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message moneydashboard.v4.GetEnvelopeAllocationByIdRequest.
 * Use `create(GetEnvelopeAllocationByIdRequestSchema)` to create a new message.
 */
export const GetEnvelopeAllocationByIdRequestSchema: GenMessage<GetEnvelopeAllocationByIdRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_envelope_allocations, 1);

/**
 * @generated from message moneydashboard.v4.GetEnvelopeAllocationByIdResponse
 */
export type GetEnvelopeAllocationByIdResponse = Message<"moneydashboard.v4.GetEnvelopeAllocationByIdResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.EnvelopeAllocation envelope_allocation = 1;
   */
  envelopeAllocation?: EnvelopeAllocation;
};

/**
 * Describes the message moneydashboard.v4.GetEnvelopeAllocationByIdResponse.
 * Use `create(GetEnvelopeAllocationByIdResponseSchema)` to create a new message.
 */
export const GetEnvelopeAllocationByIdResponseSchema: GenMessage<GetEnvelopeAllocationByIdResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_envelope_allocations, 2);

/**
 * @generated from message moneydashboard.v4.GetAllEnvelopeAllocationsRequest
 */
export type GetAllEnvelopeAllocationsRequest = Message<"moneydashboard.v4.GetAllEnvelopeAllocationsRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetAllEnvelopeAllocationsRequest.
 * Use `create(GetAllEnvelopeAllocationsRequestSchema)` to create a new message.
 */
export const GetAllEnvelopeAllocationsRequestSchema: GenMessage<GetAllEnvelopeAllocationsRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_envelope_allocations, 3);

/**
 * @generated from message moneydashboard.v4.GetAllEnvelopeAllocationsResponse
 */
export type GetAllEnvelopeAllocationsResponse = Message<"moneydashboard.v4.GetAllEnvelopeAllocationsResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.EnvelopeAllocation envelope_allocations = 1;
   */
  envelopeAllocations: EnvelopeAllocation[];
};

/**
 * Describes the message moneydashboard.v4.GetAllEnvelopeAllocationsResponse.
 * Use `create(GetAllEnvelopeAllocationsResponseSchema)` to create a new message.
 */
export const GetAllEnvelopeAllocationsResponseSchema: GenMessage<GetAllEnvelopeAllocationsResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_envelope_allocations, 4);

/**
 * @generated from message moneydashboard.v4.UpsertEnvelopeAllocationRequest
 */
export type UpsertEnvelopeAllocationRequest = Message<"moneydashboard.v4.UpsertEnvelopeAllocationRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.EnvelopeAllocation envelope_allocation = 1;
   */
  envelopeAllocation?: EnvelopeAllocation;
};

/**
 * Describes the message moneydashboard.v4.UpsertEnvelopeAllocationRequest.
 * Use `create(UpsertEnvelopeAllocationRequestSchema)` to create a new message.
 */
export const UpsertEnvelopeAllocationRequestSchema: GenMessage<UpsertEnvelopeAllocationRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_envelope_allocations, 5);

/**
 * @generated from message moneydashboard.v4.UpsertEnvelopeAllocationResponse
 */
export type UpsertEnvelopeAllocationResponse = Message<"moneydashboard.v4.UpsertEnvelopeAllocationResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertEnvelopeAllocationResponse.
 * Use `create(UpsertEnvelopeAllocationResponseSchema)` to create a new message.
 */
export const UpsertEnvelopeAllocationResponseSchema: GenMessage<UpsertEnvelopeAllocationResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_envelope_allocations, 6);

/**
 * @generated from service moneydashboard.v4.MDEnvelopeAllocationService
 */
export const MDEnvelopeAllocationService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDEnvelopeAllocationService.GetEnvelopeAllocationById
   */
  getEnvelopeAllocationById: {
    methodKind: "unary";
    input: typeof GetEnvelopeAllocationByIdRequestSchema;
    output: typeof GetEnvelopeAllocationByIdResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDEnvelopeAllocationService.GetAllEnvelopeAllocations
   */
  getAllEnvelopeAllocations: {
    methodKind: "unary";
    input: typeof GetAllEnvelopeAllocationsRequestSchema;
    output: typeof GetAllEnvelopeAllocationsResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDEnvelopeAllocationService.UpsertEnvelopeAllocation
   */
  upsertEnvelopeAllocation: {
    methodKind: "unary";
    input: typeof UpsertEnvelopeAllocationRequestSchema;
    output: typeof UpsertEnvelopeAllocationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_envelope_allocations, 0);

