// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file moneydashboard/v4/main.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { GetAllCurrenciesRequestSchema, GetAllCurrenciesResponseSchema } from "./currencies_pb";
import { file_moneydashboard_v4_currencies } from "./currencies_pb";
import type { GetProfilesRequestSchema, GetProfilesResponseSchema, GetUserRequestSchema, GetUserResponseSchema, SetActiveProfileRequestSchema, SetActiveProfileResponseSchema } from "./users_pb";
import { file_moneydashboard_v4_users } from "./users_pb";

/**
 * Describes the file moneydashboard/v4/main.proto.
 */
export const file_moneydashboard_v4_main: GenFile = /*@__PURE__*/
  fileDesc("Chxtb25leWRhc2hib2FyZC92NC9tYWluLnByb3RvEhFtb25leWRhc2hib2FyZC52NDKVAwoJTURTZXJ2aWNlEmsKEEdldEFsbEN1cnJlbmNpZXMSKi5tb25leWRhc2hib2FyZC52NC5HZXRBbGxDdXJyZW5jaWVzUmVxdWVzdBorLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEFsbEN1cnJlbmNpZXNSZXNwb25zZRJQCgdHZXRVc2VyEiEubW9uZXlkYXNoYm9hcmQudjQuR2V0VXNlclJlcXVlc3QaIi5tb25leWRhc2hib2FyZC52NC5HZXRVc2VyUmVzcG9uc2USXAoLR2V0UHJvZmlsZXMSJS5tb25leWRhc2hib2FyZC52NC5HZXRQcm9maWxlc1JlcXVlc3QaJi5tb25leWRhc2hib2FyZC52NC5HZXRQcm9maWxlc1Jlc3BvbnNlEmsKEFNldEFjdGl2ZVByb2ZpbGUSKi5tb25leWRhc2hib2FyZC52NC5TZXRBY3RpdmVQcm9maWxlUmVxdWVzdBorLm1vbmV5ZGFzaGJvYXJkLnY0LlNldEFjdGl2ZVByb2ZpbGVSZXNwb25zZUJRWk9naXRodWIuY29tL21hcmtvcm1lc2hlci9tb25leS1kYXNoYm9hcmQvaW50ZXJuYWwvYXBpX2dlbi9tb25leWRhc2hib2FyZC92NDttZHY0YgZwcm90bzM", [file_moneydashboard_v4_currencies, file_moneydashboard_v4_users]);

/**
 * @generated from service moneydashboard.v4.MDService
 */
export const MDService: GenService<{
  /**
   * currencies.proto
   *
   * @generated from rpc moneydashboard.v4.MDService.GetAllCurrencies
   */
  getAllCurrencies: {
    methodKind: "unary";
    input: typeof GetAllCurrenciesRequestSchema;
    output: typeof GetAllCurrenciesResponseSchema;
  },
  /**
   * users.proto
   *
   * @generated from rpc moneydashboard.v4.MDService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDService.GetProfiles
   */
  getProfiles: {
    methodKind: "unary";
    input: typeof GetProfilesRequestSchema;
    output: typeof GetProfilesResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDService.SetActiveProfile
   */
  setActiveProfile: {
    methodKind: "unary";
    input: typeof SetActiveProfileRequestSchema;
    output: typeof SetActiveProfileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_main, 0);

