// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file moneydashboard/v4/moneydashboard.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/moneydashboard.proto.
 */
export const file_moneydashboard_v4_moneydashboard: GenFile = /*@__PURE__*/
  fileDesc("CiZtb25leWRhc2hib2FyZC92NC9tb25leWRhc2hib2FyZC5wcm90bxIRbW9uZXlkYXNoYm9hcmQudjQiUgoEVXNlchIKCgJJRBgBIAEoCRIYChBleHRlcm5hbFVzZXJuYW1lGAIgASgJEhMKC2Rpc3BsYXlOYW1lGAMgASgJEg8KB2RlbGV0ZWQYBCABKAgiFwoVR2V0Q3VycmVudFVzZXJSZXF1ZXN0Ij8KFkdldEN1cnJlbnRVc2VyUmVzcG9uc2USJQoEdXNlchgBIAEoCzIXLm1vbmV5ZGFzaGJvYXJkLnY0LlVzZXIycgoJTURTZXJ2aWNlEmUKDkdldEN1cnJlbnRVc2VyEigubW9uZXlkYXNoYm9hcmQudjQuR2V0Q3VycmVudFVzZXJSZXF1ZXN0GikubW9uZXlkYXNoYm9hcmQudjQuR2V0Q3VycmVudFVzZXJSZXNwb25zZUJRWk9naXRodWIuY29tL21hcmtvcm1lc2hlci9tb25leS1kYXNoYm9hcmQvaW50ZXJuYWwvYXBpX2dlbi9tb25leWRhc2hib2FyZC92NDttZHY0YgZwcm90bzM");

/**
 * @generated from message moneydashboard.v4.User
 */
export type User = Message<"moneydashboard.v4.User"> & {
  /**
   * @generated from field: string ID = 1;
   */
  ID: string;

  /**
   * @generated from field: string externalUsername = 2;
   */
  externalUsername: string;

  /**
   * @generated from field: string displayName = 3;
   */
  displayName: string;

  /**
   * @generated from field: bool deleted = 4;
   */
  deleted: boolean;
};

/**
 * Describes the message moneydashboard.v4.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_moneydashboard, 0);

/**
 * @generated from message moneydashboard.v4.GetCurrentUserRequest
 */
export type GetCurrentUserRequest = Message<"moneydashboard.v4.GetCurrentUserRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetCurrentUserRequest.
 * Use `create(GetCurrentUserRequestSchema)` to create a new message.
 */
export const GetCurrentUserRequestSchema: GenMessage<GetCurrentUserRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_moneydashboard, 1);

/**
 * @generated from message moneydashboard.v4.GetCurrentUserResponse
 */
export type GetCurrentUserResponse = Message<"moneydashboard.v4.GetCurrentUserResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message moneydashboard.v4.GetCurrentUserResponse.
 * Use `create(GetCurrentUserResponseSchema)` to create a new message.
 */
export const GetCurrentUserResponseSchema: GenMessage<GetCurrentUserResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_moneydashboard, 2);

/**
 * @generated from service moneydashboard.v4.MDService
 */
export const MDService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof GetCurrentUserRequestSchema;
    output: typeof GetCurrentUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_moneydashboard, 0);

