// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/rates.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/rates.proto.
 */
export const file_moneydashboard_v4_rates: GenFile = /*@__PURE__*/
  fileDesc("Ch1tb25leWRhc2hib2FyZC92NC9yYXRlcy5wcm90bxIRbW9uZXlkYXNoYm9hcmQudjQiVQoEUmF0ZRIKCgJpZBgBIAEoCRIQCghhc3NldF9pZBgCIAEoCRITCgtjdXJyZW5jeV9pZBgDIAEoCRIMCgRkYXRlGAQgASgDEgwKBHJhdGUYBSABKAEiFwoVR2V0TGF0ZXN0UmF0ZXNSZXF1ZXN0IkAKFkdldExhdGVzdFJhdGVzUmVzcG9uc2USJgoFcmF0ZXMYASADKAsyFy5tb25leWRhc2hib2FyZC52NC5SYXRlIjoKEVVwc2VydFJhdGVSZXF1ZXN0EiUKBHJhdGUYASABKAsyFy5tb25leWRhc2hib2FyZC52NC5SYXRlIhQKElVwc2VydFJhdGVSZXNwb25zZTLRAQoNTURSYXRlU2VydmljZRJlCg5HZXRMYXRlc3RSYXRlcxIoLm1vbmV5ZGFzaGJvYXJkLnY0LkdldExhdGVzdFJhdGVzUmVxdWVzdBopLm1vbmV5ZGFzaGJvYXJkLnY0LkdldExhdGVzdFJhdGVzUmVzcG9uc2USWQoKVXBzZXJ0UmF0ZRIkLm1vbmV5ZGFzaGJvYXJkLnY0LlVwc2VydFJhdGVSZXF1ZXN0GiUubW9uZXlkYXNoYm9hcmQudjQuVXBzZXJ0UmF0ZVJlc3BvbnNlQlFaT2dpdGh1Yi5jb20vbWFya29ybWVzaGVyL21vbmV5LWRhc2hib2FyZC9pbnRlcm5hbC9hcGlfZ2VuL21vbmV5ZGFzaGJvYXJkL3Y0O21kdjRiBnByb3RvMw");

/**
 * @generated from message moneydashboard.v4.Rate
 */
export type Rate = Message<"moneydashboard.v4.Rate"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string asset_id = 2;
   */
  assetId: string;

  /**
   * @generated from field: string currency_id = 3;
   */
  currencyId: string;

  /**
   * @generated from field: int64 date = 4;
   */
  date: bigint;

  /**
   * @generated from field: double rate = 5;
   */
  rate: number;
};

/**
 * Describes the message moneydashboard.v4.Rate.
 * Use `create(RateSchema)` to create a new message.
 */
export const RateSchema: GenMessage<Rate> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_rates, 0);

/**
 * @generated from message moneydashboard.v4.GetLatestRatesRequest
 */
export type GetLatestRatesRequest = Message<"moneydashboard.v4.GetLatestRatesRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetLatestRatesRequest.
 * Use `create(GetLatestRatesRequestSchema)` to create a new message.
 */
export const GetLatestRatesRequestSchema: GenMessage<GetLatestRatesRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_rates, 1);

/**
 * @generated from message moneydashboard.v4.GetLatestRatesResponse
 */
export type GetLatestRatesResponse = Message<"moneydashboard.v4.GetLatestRatesResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.Rate rates = 1;
   */
  rates: Rate[];
};

/**
 * Describes the message moneydashboard.v4.GetLatestRatesResponse.
 * Use `create(GetLatestRatesResponseSchema)` to create a new message.
 */
export const GetLatestRatesResponseSchema: GenMessage<GetLatestRatesResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_rates, 2);

/**
 * @generated from message moneydashboard.v4.UpsertRateRequest
 */
export type UpsertRateRequest = Message<"moneydashboard.v4.UpsertRateRequest"> & {
  /**
   * @generated from field: moneydashboard.v4.Rate rate = 1;
   */
  rate?: Rate;
};

/**
 * Describes the message moneydashboard.v4.UpsertRateRequest.
 * Use `create(UpsertRateRequestSchema)` to create a new message.
 */
export const UpsertRateRequestSchema: GenMessage<UpsertRateRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_rates, 3);

/**
 * @generated from message moneydashboard.v4.UpsertRateResponse
 */
export type UpsertRateResponse = Message<"moneydashboard.v4.UpsertRateResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.UpsertRateResponse.
 * Use `create(UpsertRateResponseSchema)` to create a new message.
 */
export const UpsertRateResponseSchema: GenMessage<UpsertRateResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_rates, 4);

/**
 * @generated from service moneydashboard.v4.MDRateService
 */
export const MDRateService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDRateService.GetLatestRates
   */
  getLatestRates: {
    methodKind: "unary";
    input: typeof GetLatestRatesRequestSchema;
    output: typeof GetLatestRatesResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDRateService.UpsertRate
   */
  upsertRate: {
    methodKind: "unary";
    input: typeof UpsertRateRequestSchema;
    output: typeof UpsertRateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_rates, 0);

