// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file moneydashboard/v4/reporting.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Holding } from "./holdings_pb.js";
import { file_moneydashboard_v4_holdings } from "./holdings_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/reporting.proto.
 */
export const file_moneydashboard_v4_reporting: GenFile = /*@__PURE__*/
  fileDesc("CiFtb25leWRhc2hib2FyZC92NC9yZXBvcnRpbmcucHJvdG8SEW1vbmV5ZGFzaGJvYXJkLnY0ImcKDkhvbGRpbmdCYWxhbmNlEisKB2hvbGRpbmcYASABKAsyGi5tb25leWRhc2hib2FyZC52NC5Ib2xkaW5nEhMKC3Jhd19iYWxhbmNlGAIgASgBEhMKC2dicF9iYWxhbmNlGAMgASgBIhsKGUdldEhvbGRpbmdCYWxhbmNlc1JlcXVlc3QiUQoaR2V0SG9sZGluZ0JhbGFuY2VzUmVzcG9uc2USMwoIYmFsYW5jZXMYASADKAsyIS5tb25leWRhc2hib2FyZC52NC5Ib2xkaW5nQmFsYW5jZTKHAQoSTURSZXBvcnRpbmdTZXJ2aWNlEnEKEkdldEhvbGRpbmdCYWxhbmNlcxIsLm1vbmV5ZGFzaGJvYXJkLnY0LkdldEhvbGRpbmdCYWxhbmNlc1JlcXVlc3QaLS5tb25leWRhc2hib2FyZC52NC5HZXRIb2xkaW5nQmFsYW5jZXNSZXNwb25zZUJRWk9naXRodWIuY29tL21hcmtvcm1lc2hlci9tb25leS1kYXNoYm9hcmQvaW50ZXJuYWwvYXBpX2dlbi9tb25leWRhc2hib2FyZC92NDttZHY0YgZwcm90bzM", [file_moneydashboard_v4_holdings]);

/**
 * @generated from message moneydashboard.v4.HoldingBalance
 */
export type HoldingBalance = Message<"moneydashboard.v4.HoldingBalance"> & {
  /**
   * @generated from field: moneydashboard.v4.Holding holding = 1;
   */
  holding?: Holding;

  /**
   * @generated from field: double raw_balance = 2;
   */
  rawBalance: number;

  /**
   * @generated from field: double gbp_balance = 3;
   */
  gbpBalance: number;
};

/**
 * Describes the message moneydashboard.v4.HoldingBalance.
 * Use `create(HoldingBalanceSchema)` to create a new message.
 */
export const HoldingBalanceSchema: GenMessage<HoldingBalance> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_reporting, 0);

/**
 * @generated from message moneydashboard.v4.GetHoldingBalancesRequest
 */
export type GetHoldingBalancesRequest = Message<"moneydashboard.v4.GetHoldingBalancesRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetHoldingBalancesRequest.
 * Use `create(GetHoldingBalancesRequestSchema)` to create a new message.
 */
export const GetHoldingBalancesRequestSchema: GenMessage<GetHoldingBalancesRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_reporting, 1);

/**
 * @generated from message moneydashboard.v4.GetHoldingBalancesResponse
 */
export type GetHoldingBalancesResponse = Message<"moneydashboard.v4.GetHoldingBalancesResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.HoldingBalance balances = 1;
   */
  balances: HoldingBalance[];
};

/**
 * Describes the message moneydashboard.v4.GetHoldingBalancesResponse.
 * Use `create(GetHoldingBalancesResponseSchema)` to create a new message.
 */
export const GetHoldingBalancesResponseSchema: GenMessage<GetHoldingBalancesResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_reporting, 2);

/**
 * @generated from service moneydashboard.v4.MDReportingService
 */
export const MDReportingService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDReportingService.GetHoldingBalances
   */
  getHoldingBalances: {
    methodKind: "unary";
    input: typeof GetHoldingBalancesRequestSchema;
    output: typeof GetHoldingBalancesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_reporting, 0);

