// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file moneydashboard/v4/users.proto (package moneydashboard.v4, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moneydashboard/v4/users.proto.
 */
export const file_moneydashboard_v4_users: GenFile = /*@__PURE__*/
  fileDesc("Ch1tb25leWRhc2hib2FyZC92NC91c2Vycy5wcm90bxIRbW9uZXlkYXNoYm9hcmQudjQiiAEKBFVzZXISCgoCaWQYASABKAkSGQoRZXh0ZXJuYWxfdXNlcm5hbWUYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJEg8KB2RlbGV0ZWQYBCABKAgSMgoOYWN0aXZlX3Byb2ZpbGUYBSABKAsyGi5tb25leWRhc2hib2FyZC52NC5Qcm9maWxlIjQKB1Byb2ZpbGUSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIPCgdkZWxldGVkGAMgASgIIhAKDkdldFVzZXJSZXF1ZXN0IjgKD0dldFVzZXJSZXNwb25zZRIlCgR1c2VyGAEgASgLMhcubW9uZXlkYXNoYm9hcmQudjQuVXNlciIUChJHZXRQcm9maWxlc1JlcXVlc3QiQwoTR2V0UHJvZmlsZXNSZXNwb25zZRIsCghwcm9maWxlcxgBIAMoCzIaLm1vbmV5ZGFzaGJvYXJkLnY0LlByb2ZpbGUiLQoXU2V0QWN0aXZlUHJvZmlsZVJlcXVlc3QSEgoKcHJvZmlsZV9pZBgBIAEoCSIaChhTZXRBY3RpdmVQcm9maWxlUmVzcG9uc2UyrAIKDU1EVXNlclNlcnZpY2USUAoHR2V0VXNlchIhLm1vbmV5ZGFzaGJvYXJkLnY0LkdldFVzZXJSZXF1ZXN0GiIubW9uZXlkYXNoYm9hcmQudjQuR2V0VXNlclJlc3BvbnNlElwKC0dldFByb2ZpbGVzEiUubW9uZXlkYXNoYm9hcmQudjQuR2V0UHJvZmlsZXNSZXF1ZXN0GiYubW9uZXlkYXNoYm9hcmQudjQuR2V0UHJvZmlsZXNSZXNwb25zZRJrChBTZXRBY3RpdmVQcm9maWxlEioubW9uZXlkYXNoYm9hcmQudjQuU2V0QWN0aXZlUHJvZmlsZVJlcXVlc3QaKy5tb25leWRhc2hib2FyZC52NC5TZXRBY3RpdmVQcm9maWxlUmVzcG9uc2VCUVpPZ2l0aHViLmNvbS9tYXJrb3JtZXNoZXIvbW9uZXktZGFzaGJvYXJkL2ludGVybmFsL2FwaV9nZW4vbW9uZXlkYXNoYm9hcmQvdjQ7bWR2NGIGcHJvdG8z");

/**
 * @generated from message moneydashboard.v4.User
 */
export type User = Message<"moneydashboard.v4.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string external_username = 2;
   */
  externalUsername: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: bool deleted = 4;
   */
  deleted: boolean;

  /**
   * @generated from field: moneydashboard.v4.Profile active_profile = 5;
   */
  activeProfile?: Profile;
};

/**
 * Describes the message moneydashboard.v4.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 0);

/**
 * @generated from message moneydashboard.v4.Profile
 */
export type Profile = Message<"moneydashboard.v4.Profile"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bool deleted = 3;
   */
  deleted: boolean;
};

/**
 * Describes the message moneydashboard.v4.Profile.
 * Use `create(ProfileSchema)` to create a new message.
 */
export const ProfileSchema: GenMessage<Profile> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 1);

/**
 * @generated from message moneydashboard.v4.GetUserRequest
 */
export type GetUserRequest = Message<"moneydashboard.v4.GetUserRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 2);

/**
 * @generated from message moneydashboard.v4.GetUserResponse
 */
export type GetUserResponse = Message<"moneydashboard.v4.GetUserResponse"> & {
  /**
   * @generated from field: moneydashboard.v4.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message moneydashboard.v4.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 3);

/**
 * @generated from message moneydashboard.v4.GetProfilesRequest
 */
export type GetProfilesRequest = Message<"moneydashboard.v4.GetProfilesRequest"> & {
};

/**
 * Describes the message moneydashboard.v4.GetProfilesRequest.
 * Use `create(GetProfilesRequestSchema)` to create a new message.
 */
export const GetProfilesRequestSchema: GenMessage<GetProfilesRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 4);

/**
 * @generated from message moneydashboard.v4.GetProfilesResponse
 */
export type GetProfilesResponse = Message<"moneydashboard.v4.GetProfilesResponse"> & {
  /**
   * @generated from field: repeated moneydashboard.v4.Profile profiles = 1;
   */
  profiles: Profile[];
};

/**
 * Describes the message moneydashboard.v4.GetProfilesResponse.
 * Use `create(GetProfilesResponseSchema)` to create a new message.
 */
export const GetProfilesResponseSchema: GenMessage<GetProfilesResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 5);

/**
 * @generated from message moneydashboard.v4.SetActiveProfileRequest
 */
export type SetActiveProfileRequest = Message<"moneydashboard.v4.SetActiveProfileRequest"> & {
  /**
   * @generated from field: string profile_id = 1;
   */
  profileId: string;
};

/**
 * Describes the message moneydashboard.v4.SetActiveProfileRequest.
 * Use `create(SetActiveProfileRequestSchema)` to create a new message.
 */
export const SetActiveProfileRequestSchema: GenMessage<SetActiveProfileRequest> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 6);

/**
 * @generated from message moneydashboard.v4.SetActiveProfileResponse
 */
export type SetActiveProfileResponse = Message<"moneydashboard.v4.SetActiveProfileResponse"> & {
};

/**
 * Describes the message moneydashboard.v4.SetActiveProfileResponse.
 * Use `create(SetActiveProfileResponseSchema)` to create a new message.
 */
export const SetActiveProfileResponseSchema: GenMessage<SetActiveProfileResponse> = /*@__PURE__*/
  messageDesc(file_moneydashboard_v4_users, 7);

/**
 * @generated from service moneydashboard.v4.MDUserService
 */
export const MDUserService: GenService<{
  /**
   * @generated from rpc moneydashboard.v4.MDUserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDUserService.GetProfiles
   */
  getProfiles: {
    methodKind: "unary";
    input: typeof GetProfilesRequestSchema;
    output: typeof GetProfilesResponseSchema;
  },
  /**
   * @generated from rpc moneydashboard.v4.MDUserService.SetActiveProfile
   */
  setActiveProfile: {
    methodKind: "unary";
    input: typeof SetActiveProfileRequestSchema;
    output: typeof SetActiveProfileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_moneydashboard_v4_users, 0);

