// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: moneydashboard/v4/transactions.proto

package mdv4connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v4 "github.com/markormesher/money-dashboard/internal/api_gen/moneydashboard/v4"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MDTransactionServiceName is the fully-qualified name of the MDTransactionService service.
	MDTransactionServiceName = "moneydashboard.v4.MDTransactionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MDTransactionServiceGetTransactionByIdProcedure is the fully-qualified name of the
	// MDTransactionService's GetTransactionById RPC.
	MDTransactionServiceGetTransactionByIdProcedure = "/moneydashboard.v4.MDTransactionService/GetTransactionById"
	// MDTransactionServiceGetTransactionPageProcedure is the fully-qualified name of the
	// MDTransactionService's GetTransactionPage RPC.
	MDTransactionServiceGetTransactionPageProcedure = "/moneydashboard.v4.MDTransactionService/GetTransactionPage"
	// MDTransactionServiceUpsertTransactionProcedure is the fully-qualified name of the
	// MDTransactionService's UpsertTransaction RPC.
	MDTransactionServiceUpsertTransactionProcedure = "/moneydashboard.v4.MDTransactionService/UpsertTransaction"
)

// MDTransactionServiceClient is a client for the moneydashboard.v4.MDTransactionService service.
type MDTransactionServiceClient interface {
	GetTransactionById(context.Context, *connect.Request[v4.GetTransactionByIdRequest]) (*connect.Response[v4.GetTransactionByIdResponse], error)
	GetTransactionPage(context.Context, *connect.Request[v4.GetTransactionPageRequest]) (*connect.Response[v4.GetTransactionPageResponse], error)
	UpsertTransaction(context.Context, *connect.Request[v4.UpsertTransactionRequest]) (*connect.Response[v4.UpsertTransactionResponse], error)
}

// NewMDTransactionServiceClient constructs a client for the moneydashboard.v4.MDTransactionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMDTransactionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MDTransactionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mDTransactionServiceMethods := v4.File_moneydashboard_v4_transactions_proto.Services().ByName("MDTransactionService").Methods()
	return &mDTransactionServiceClient{
		getTransactionById: connect.NewClient[v4.GetTransactionByIdRequest, v4.GetTransactionByIdResponse](
			httpClient,
			baseURL+MDTransactionServiceGetTransactionByIdProcedure,
			connect.WithSchema(mDTransactionServiceMethods.ByName("GetTransactionById")),
			connect.WithClientOptions(opts...),
		),
		getTransactionPage: connect.NewClient[v4.GetTransactionPageRequest, v4.GetTransactionPageResponse](
			httpClient,
			baseURL+MDTransactionServiceGetTransactionPageProcedure,
			connect.WithSchema(mDTransactionServiceMethods.ByName("GetTransactionPage")),
			connect.WithClientOptions(opts...),
		),
		upsertTransaction: connect.NewClient[v4.UpsertTransactionRequest, v4.UpsertTransactionResponse](
			httpClient,
			baseURL+MDTransactionServiceUpsertTransactionProcedure,
			connect.WithSchema(mDTransactionServiceMethods.ByName("UpsertTransaction")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mDTransactionServiceClient implements MDTransactionServiceClient.
type mDTransactionServiceClient struct {
	getTransactionById *connect.Client[v4.GetTransactionByIdRequest, v4.GetTransactionByIdResponse]
	getTransactionPage *connect.Client[v4.GetTransactionPageRequest, v4.GetTransactionPageResponse]
	upsertTransaction  *connect.Client[v4.UpsertTransactionRequest, v4.UpsertTransactionResponse]
}

// GetTransactionById calls moneydashboard.v4.MDTransactionService.GetTransactionById.
func (c *mDTransactionServiceClient) GetTransactionById(ctx context.Context, req *connect.Request[v4.GetTransactionByIdRequest]) (*connect.Response[v4.GetTransactionByIdResponse], error) {
	return c.getTransactionById.CallUnary(ctx, req)
}

// GetTransactionPage calls moneydashboard.v4.MDTransactionService.GetTransactionPage.
func (c *mDTransactionServiceClient) GetTransactionPage(ctx context.Context, req *connect.Request[v4.GetTransactionPageRequest]) (*connect.Response[v4.GetTransactionPageResponse], error) {
	return c.getTransactionPage.CallUnary(ctx, req)
}

// UpsertTransaction calls moneydashboard.v4.MDTransactionService.UpsertTransaction.
func (c *mDTransactionServiceClient) UpsertTransaction(ctx context.Context, req *connect.Request[v4.UpsertTransactionRequest]) (*connect.Response[v4.UpsertTransactionResponse], error) {
	return c.upsertTransaction.CallUnary(ctx, req)
}

// MDTransactionServiceHandler is an implementation of the moneydashboard.v4.MDTransactionService
// service.
type MDTransactionServiceHandler interface {
	GetTransactionById(context.Context, *connect.Request[v4.GetTransactionByIdRequest]) (*connect.Response[v4.GetTransactionByIdResponse], error)
	GetTransactionPage(context.Context, *connect.Request[v4.GetTransactionPageRequest]) (*connect.Response[v4.GetTransactionPageResponse], error)
	UpsertTransaction(context.Context, *connect.Request[v4.UpsertTransactionRequest]) (*connect.Response[v4.UpsertTransactionResponse], error)
}

// NewMDTransactionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMDTransactionServiceHandler(svc MDTransactionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mDTransactionServiceMethods := v4.File_moneydashboard_v4_transactions_proto.Services().ByName("MDTransactionService").Methods()
	mDTransactionServiceGetTransactionByIdHandler := connect.NewUnaryHandler(
		MDTransactionServiceGetTransactionByIdProcedure,
		svc.GetTransactionById,
		connect.WithSchema(mDTransactionServiceMethods.ByName("GetTransactionById")),
		connect.WithHandlerOptions(opts...),
	)
	mDTransactionServiceGetTransactionPageHandler := connect.NewUnaryHandler(
		MDTransactionServiceGetTransactionPageProcedure,
		svc.GetTransactionPage,
		connect.WithSchema(mDTransactionServiceMethods.ByName("GetTransactionPage")),
		connect.WithHandlerOptions(opts...),
	)
	mDTransactionServiceUpsertTransactionHandler := connect.NewUnaryHandler(
		MDTransactionServiceUpsertTransactionProcedure,
		svc.UpsertTransaction,
		connect.WithSchema(mDTransactionServiceMethods.ByName("UpsertTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	return "/moneydashboard.v4.MDTransactionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MDTransactionServiceGetTransactionByIdProcedure:
			mDTransactionServiceGetTransactionByIdHandler.ServeHTTP(w, r)
		case MDTransactionServiceGetTransactionPageProcedure:
			mDTransactionServiceGetTransactionPageHandler.ServeHTTP(w, r)
		case MDTransactionServiceUpsertTransactionProcedure:
			mDTransactionServiceUpsertTransactionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMDTransactionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMDTransactionServiceHandler struct{}

func (UnimplementedMDTransactionServiceHandler) GetTransactionById(context.Context, *connect.Request[v4.GetTransactionByIdRequest]) (*connect.Response[v4.GetTransactionByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moneydashboard.v4.MDTransactionService.GetTransactionById is not implemented"))
}

func (UnimplementedMDTransactionServiceHandler) GetTransactionPage(context.Context, *connect.Request[v4.GetTransactionPageRequest]) (*connect.Response[v4.GetTransactionPageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moneydashboard.v4.MDTransactionService.GetTransactionPage is not implemented"))
}

func (UnimplementedMDTransactionServiceHandler) UpsertTransaction(context.Context, *connect.Request[v4.UpsertTransactionRequest]) (*connect.Response[v4.UpsertTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moneydashboard.v4.MDTransactionService.UpsertTransaction is not implemented"))
}
