# This file is maintained by Tedium - manual edits will be overwritten!

version: "2.1"
jobs:
  cachekey:
    docker:
      - image: cimg/base:2026.04@sha256:c7693014a5fe7f5c95ac54590b54e2b183995241e082eb20377761916477a3e4
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task cachekey
      - persist_to_workspace:
          root: .
          paths:
            - ./.task-meta-cachekey*
  checkout:
    docker:
      - image: cimg/base:2026.04@sha256:c7693014a5fe7f5c95ac54590b54e2b183995241e082eb20377761916477a3e4
    steps:
      - checkout:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .
  ci-all:
    docker:
      - image: cimg/base:2026.04@sha256:c7693014a5fe7f5c95ac54590b54e2b183995241e082eb20377761916477a3e4
    steps:
      - run:
          command: echo "Done"
  deps-go:
    docker:
      - image: docker.io/golang:1.26.3@sha256:2d6c80227255c3112a4d08e67ba98e58efd3846daf15d9d7d4c389565d881b1a
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
            - deps-go-v7-
      - run:
          command: |-
            export GOPATH=/.go
            export GOCACHE=/.gocache
            ./task deps-go
      - save_cache:
          key: deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
          paths:
            - /.go
            - /.gocache
  deps-js:
    docker:
      - image: docker.io/node:24.16.0-slim@sha256:242549cd46785b480c832479a730f4f2a20865d61ea2e404fdb2a5c3d3b73ecf
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-js-v7-{{ checksum ".task-meta-cachekey-js" }}
            - deps-js-v7-
      - run:
          command: |-
            npm install -g --force yarn pnpm
            ./task deps-js
      - save_cache:
          key: deps-js-v7-{{ checksum ".task-meta-cachekey-js" }}
          paths:
            - /usr/local/lib/node_modules
            - frontend/node_modules
  fetch-task:
    docker:
      - image: ghcr.io/markormesher/task-fetcher:v0.6.14@sha256:8765e5e5da8498074a2b7d2e2a083c6e7ce7859659053178178e04c32299997d
    steps:
      - attach_workspace:
          at: .
      - run:
          command: cp /task .
      - persist_to_workspace:
          root: .
          paths:
            - ./task
  imgbuild-imgpush:
    docker:
      - image: cimg/base:2026.04@sha256:c7693014a5fe7f5c95ac54590b54e2b183995241e082eb20377761916477a3e4
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |-
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            ./task imgbuild
            ./task imgpush
  imgrefs:
    docker:
      - image: docker.io/alpine/git:v2.52.0@sha256:8786a6a02273827d0aa039d174aacd5e017fcce9aba0af62596d991970cab01a
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task imgrefs
      - persist_to_workspace:
          root: .
          paths:
            - ./.task-meta-imgrefs
            - ./**/.task-meta-imgrefs
  lint-buf:
    docker:
      - image: docker.io/bufbuild/buf:1.70.0@sha256:6e5b0946e9ad260c9b0a2908148d081834bca26897a924d177e5e5a31eb65b33
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-buf-v7-{{ checksum ".task-meta-cachekey-buf" }}
            - deps-buf-v7-
      - run:
          command: ./task lint-buf
  lint-go:
    docker:
      - image: docker.io/golang:1.26.3@sha256:2d6c80227255c3112a4d08e67ba98e58efd3846daf15d9d7d4c389565d881b1a
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
            - deps-go-v7-
      - run:
          command: |-
            export GOPATH=/.go
            export GOCACHE=/.gocache
            ./task lint-go
  lint-js:
    docker:
      - image: docker.io/node:24.16.0-slim@sha256:242549cd46785b480c832479a730f4f2a20865d61ea2e404fdb2a5c3d3b73ecf
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-js-v7-{{ checksum ".task-meta-cachekey-js" }}
            - deps-js-v7-
      - run:
          command: |-
            npm install -g --force yarn pnpm
            ./task lint-js
workflows:
  version: 2
  main:
    jobs:
      - checkout:
          requires: []
          filters:
            tags:
              only: /.*/
      - fetch-task:
          requires: []
          filters:
            tags:
              only: /.*/
      - imgrefs:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - lint-buf:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - cachekey:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - deps-go:
          requires:
            - cachekey
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - deps-js:
          requires:
            - cachekey
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - lint-go:
          requires:
            - checkout
            - deps-go
            - fetch-task
          filters:
            tags:
              only: /.*/
      - lint-js:
          requires:
            - checkout
            - deps-js
            - fetch-task
          filters:
            tags:
              only: /.*/
      - imgbuild-imgpush:
          requires:
            - checkout
            - fetch-task
            - imgrefs
            - lint-buf
            - lint-go
            - lint-js
          filters:
            tags:
              only: /.*/
      - ci-all:
          requires:
            - deps-go
            - deps-js
            - imgbuild-imgpush
            - imgrefs
            - lint-buf
            - lint-go
            - lint-js
          filters:
            tags:
              only: /.*/
