ALTER TABLE transaction ALTER COLUMN amount TYPE NUMERIC(20, 10);
ALTER TABLE transaction ALTER COLUMN unit_value TYPE NUMERIC(20, 10);

ALTER TABLE envelope_transfer ALTER COLUMN amount TYPE NUMERIC(20, 10);

ALTER TABLE legacy_budget ALTER COLUMN amount TYPE NUMERIC(20, 10);

ALTER TABLE rate ALTER COLUMN rate TYPE NUMERIC(20, 10);
