# This file is maintained by Tedium - manual edits will be overwritten!
name: CI
"on":
  - push
jobs:
  check-backend-go:
    runs-on: ubuntu-latest
    container:
      image: docker.io/golang:1.27.0@sha256:65b6f280bf050ec5af12716857e8ea8439d694dbba8f31ceeb7630670071f2bb
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cacheload-backend-go
      - run: ./task -s deps-backend-go
      - run: ./task -s lint-backend-go
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cachesave-backend-go
  check-frontend-js:
    runs-on: ubuntu-latest
    container:
      image: docker.io/node:25.9.0@sha256:78839ac448c23517f8eab2e8f7943d9b4f73979eb7f8bed2c73dbf72ff869e7b
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - run: npm install -g --force yarn pnpm
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cacheload-frontend-js
      - run: ./task -s deps-frontend-js
      - run: ./task -s lint-frontend-js
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cachesave-frontend-js
  check-proto-buf:
    runs-on: ubuntu-latest
    container:
      image: docker.io/bufbuild/buf:1.72.0@sha256:65bd496a89c762ad7151ca9e7d885a45dacb3671a8e8ec39738b9f844d3405ea
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - run: ./task -s lint-proto-buf
  ci-all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check-backend-go
      - check-frontend-js
      - check-proto-buf
      - img-root
    container:
      image: docker.io/busybox:1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
    steps:
      - run: |2
          results=$(echo '${{ toJson(needs) }}' | (grep '"result"' || echo))
          if echo "$results" | grep -q "failure\|cancelled\|skipped"; then
            echo "One or more jobs failed, were cancelled, or were skipped" >&2
            exit 1
          fi
          echo "All jobs passed"
  img-root:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - run: buildah login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
      - run: ./task -s imgrefs-root
      - run: ./task -s imgbuild-root
      - run: ./task -s imgpush-root
