# This file is maintained by Tedium - manual edits will be overwritten!
name: CI
"on":
  - push
jobs:
  check-buf:
    runs-on: ubuntu-latest
    container:
      image: docker.io/bufbuild/buf:1.61.0
    steps:
      - uses: markormesher/ci-resources/setup@1f35cae2345536f9b1bbe3f5655538ba459883d9 # v0.6.0
      - run: ./task lint-buf
  check-go:
    runs-on: ubuntu-latest
    container:
      image: docker.io/golang:1.26.0
    steps:
      - uses: markormesher/ci-resources/setup@1f35cae2345536f9b1bbe3f5655538ba459883d9 # v0.6.0
      - run: ./task deps-go
      - run: ./task lint-go
  check-js:
    runs-on: ubuntu-latest
    container:
      image: docker.io/node:25.9.0@sha256:78839ac448c23517f8eab2e8f7943d9b4f73979eb7f8bed2c73dbf72ff869e7b
    steps:
      - uses: markormesher/ci-resources/setup@1f35cae2345536f9b1bbe3f5655538ba459883d9 # v0.6.0
      - run: npm install -g --force yarn pnpm
      - run: ./task deps-js
      - run: ./task lint-js
  ci-all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check-buf
      - check-go
      - check-js
      - img-build-push
    container:
      image: docker.io/busybox:1.37.0@sha256:9532d8c39891ca2ecde4d30d7710e01fb739c87a8b9299685c63704296b16028
    steps:
      - run: |2
          results=$(echo '${{ toJson(needs) }}' | (grep '"result"' || echo))
          if echo "$results" | grep -q "failure\|cancelled\|skipped"; then
            echo "One or more jobs failed, were cancelled, or were skipped" >&2
            exit 1
          fi
          echo "All jobs passed"
  img-build-push:
    runs-on: ubuntu-latest
    needs:
      - check-buf
      - check-go
      - check-js
    permissions:
      packages: write
    steps:
      - uses: markormesher/ci-resources/setup@1f35cae2345536f9b1bbe3f5655538ba459883d9 # v0.6.0
      - run: buildah login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
      - run: ./task imgrefs
      - run: ./task imgbuild
      - run: ./task imgpush
