# This file is maintained by Tedium - manual edits will be overwritten!
name: CI
"on":
  - push
jobs:
  check-buf:
    runs-on: ubuntu-latest
    container:
      image: docker.io/bufbuild/buf:1.71.0@sha256:7f3e3dfb8650f39878625bbc9f2016a51a781693b209165671d5a61d11c74992
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - run: ./task lint-buf
  check-go:
    runs-on: ubuntu-latest
    container:
      image: docker.io/golang:1.26.5@sha256:079e59808d2d252516e27e3f3a9c003740dee7f75e55aa71528766d52bcfc16a
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - run: ./task deps-go
      - run: ./task lint-go
  check-js:
    runs-on: ubuntu-latest
    container:
      image: docker.io/node:25.9.0@sha256:78839ac448c23517f8eab2e8f7943d9b4f73979eb7f8bed2c73dbf72ff869e7b
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - run: npm install -g --force yarn pnpm
      - run: ./task deps-js
      - run: ./task lint-js
  ci-all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check-buf
      - check-go
      - check-js
      - img-build-push
    container:
      image: docker.io/busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
    steps:
      - run: |2
          results=$(echo '${{ toJson(needs) }}' | (grep '"result"' || echo))
          if echo "$results" | grep -q "failure\|cancelled\|skipped"; then
            echo "One or more jobs failed, were cancelled, or were skipped" >&2
            exit 1
          fi
          echo "All jobs passed"
  img-build-push:
    runs-on: ubuntu-latest
    needs:
      - check-buf
      - check-go
      - check-js
    permissions:
      packages: write
    steps:
      - uses: markormesher/ci-resources/setup@c733feb84c0204cdc0bd46f6f8ca557209bb5c33 # v0.8.0
      - run: buildah login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
      - run: ./task imgrefs
      - run: ./task imgbuild
      - run: ./task imgpush
